// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameAddressArea = "address_areas"

// AddressArea mapped from table <address_areas>
type AddressArea struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AreaName  string    `gorm:"column:area_name" json:"area_name"`
	CreatedAt time.Time `gorm:"column:createdAt" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updatedAt" json:"updatedAt"`
}

// TableName AddressArea's table name
func (*AddressArea) TableName() string {
	return TableNameAddressArea
}
