// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameAssigmentDriverDaliy = "assigment_driver_daliy"

// AssigmentDriverDaliy mapped from table <assigment_driver_daliy>
type AssigmentDriverDaliy struct {
	IDServiceDaily      int32     `gorm:"column:id_service_daily;primaryKey;autoIncrement:true" json:"id_service_daily"`
	ServiceDriversID    int32     `gorm:"column:service_drivers_id" json:"service_drivers_id"`
	StartDate           string    `gorm:"column:start_date" json:"start_date"`
	EndDate             string    `gorm:"column:end_date" json:"end_date"`
	StatusDriver        int32     `gorm:"column:status_driver;default:1" json:"status_driver"`
	CreatedAt           time.Time `gorm:"column:created_at" json:"created_at"`
	UpdateAt            time.Time `gorm:"column:update_at" json:"update_at"`
	IDIwoDaily          int32     `gorm:"column:id_iwo_daily" json:"id_iwo_daily"`
	IDServiceUsersDaily int32     `gorm:"column:id_service_users_daily" json:"id_service_users_daily"`
	TotalHariKerja      int32     `gorm:"column:total_hari_kerja" json:"total_hari_kerja"`
	StartDateYmd        string    `gorm:"column:start_date_ymd" json:"start_date_ymd"`
	EndDateYmd          string    `gorm:"column:end_date_ymd" json:"end_date_ymd"`
}

// TableName AssigmentDriverDaliy's table name
func (*AssigmentDriverDaliy) TableName() string {
	return TableNameAssigmentDriverDaliy
}
