// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameAttendanceFee = "attendance_fees"

// AttendanceFee mapped from table <attendance_fees>
type AttendanceFee struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AttendanceFeeType string    `gorm:"column:attendance_fee_type" json:"attendance_fee_type"`
	AttendanceFee     string    `gorm:"column:attendance_fee" json:"attendance_fee"`
	CreatedAt         time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName AttendanceFee's table name
func (*AttendanceFee) TableName() string {
	return TableNameAttendanceFee
}
