// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameBpjsEmployment = "bpjs_employments"

// BpjsEmployment mapped from table <bpjs_employments>
type BpjsEmployment struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
	CompanyFee  string    `gorm:"column:company_fee" json:"company_fee"`
	EmployeeFee string    `gorm:"column:employee_fee" json:"employee_fee"`
}

// TableName BpjsEmployment's table name
func (*BpjsEmployment) TableName() string {
	return TableNameBpjsEmployment
}
