// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameBpjsMedical = "bpjs_medicals"

// BpjsMedical mapped from table <bpjs_medicals>
type BpjsMedical struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
	CompanyFee  string    `gorm:"column:company_fee" json:"company_fee"`
	EmployeeFee string    `gorm:"column:employee_fee" json:"employee_fee"`
}

// TableName BpjsMedical's table name
func (*BpjsMedical) TableName() string {
	return TableNameBpjsMedical
}
