// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameDailyExpense = "daily_expenses"

// DailyExpense mapped from table <daily_expenses>
type DailyExpense struct {
	ID                 int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IDUser             int32     `gorm:"column:id_user" json:"id_user"`
	IDDriver           int32     `gorm:"column:id_driver" json:"id_driver"`
	DateTimestamp      int32     `gorm:"column:date_timestamp" json:"date_timestamp"`
	ExpensesValue      int32     `gorm:"column:expenses_value" json:"expenses_value"`
	ExpensesType       int32     `gorm:"column:expenses_type;comment:0:parkir|1:tol|2:lainlain" json:"expenses_type"` // 0:parkir|1:tol|2:lainlain
	ExpensesPhoto      string    `gorm:"column:expenses_photo" json:"expenses_photo"`
	CreatedAt          time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt          time.Time `gorm:"column:updated_at" json:"updated_at"`
	ExpensesNotes      string    `gorm:"column:expenses_notes" json:"expenses_notes"`
	Status             int32     `gorm:"column:status;default:1" json:"status"`
	DateExpenses       string    `gorm:"column:date_expenses" json:"date_expenses"`
	Remarks            int32     `gorm:"column:remarks" json:"remarks"`
	ExpensesPhotoCloud string    `gorm:"column:expenses_photo_cloud" json:"expenses_photo_cloud"`
	LokasiExpenses     string    `gorm:"column:lokasi_expenses" json:"lokasi_expenses"`
	StatusBon          string    `gorm:"column:status_bon" json:"status_bon"`
	IDExpensesMysql    int32     `gorm:"column:id_expenses_mysql" json:"id_expenses_mysql"`
}

// TableName DailyExpense's table name
func (*DailyExpense) TableName() string {
	return TableNameDailyExpense
}
