// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameDailyExpensesArchive = "daily_expenses_archives"

// DailyExpensesArchive mapped from table <daily_expenses_archives>
type DailyExpensesArchive struct {
	ID                     int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Ppn                    string    `gorm:"column:ppn" json:"ppn"`
	Periode                string    `gorm:"column:periode" json:"periode"`
	Pph23                  string    `gorm:"column:pph23" json:"pph23"`
	Total                  string    `gorm:"column:total" json:"total"`
	AgentFee               string    `gorm:"column:agent_fee" json:"agent_fee"`
	AgentFeeValue          string    `gorm:"column:agent_fee_value" json:"agent_fee_value"`
	AttnInvoice            string    `gorm:"column:attn_invoice" json:"attn_invoice"`
	CompanyID              int32     `gorm:"column:company_id" json:"company_id"`
	CreatedAt              time.Time `gorm:"column:created_at" json:"created_at"`
	EndTimestamp           string    `gorm:"column:end_timestamp" json:"end_timestamp"`
	ExpensesJSON           string    `gorm:"column:expenses_json" json:"expenses_json"`
	InternalCompanyID      int32     `gorm:"column:internal_company_id" json:"internal_company_id"`
	InvoiceDate            string    `gorm:"column:invoice_date" json:"invoice_date"`
	InvoiceNo              string    `gorm:"column:invoice_no" json:"invoice_no"`
	InvoiceNoPpn           string    `gorm:"column:invoice_no_ppn" json:"invoice_no_ppn"`
	IwoID                  int32     `gorm:"column:iwo_id" json:"iwo_id"`
	JobHolder              string    `gorm:"column:job_holder" json:"job_holder"`
	MonthTimestamp         string    `gorm:"column:month_timestamp" json:"month_timestamp"`
	ServiceDriversID       int32     `gorm:"column:service_drivers_id" json:"service_drivers_id"`
	StartTimestamp         string    `gorm:"column:start_timestamp" json:"start_timestamp"`
	TotalIsiBensin         string    `gorm:"column:total_isi_bensin" json:"total_isi_bensin"`
	TotalLainLain          string    `gorm:"column:total_lain_lain" json:"total_lain_lain"`
	TotalParkirLiar        string    `gorm:"column:total_parkir_liar" json:"total_parkir_liar"`
	TotalParkirUmum        string    `gorm:"column:total_parkir_umum" json:"total_parkir_umum"`
	TotalTollFee           string    `gorm:"column:total_toll_fee" json:"total_toll_fee"`
	UpdatedAt              time.Time `gorm:"column:updated_at" json:"updated_at"`
	TotalIsiAngin          string    `gorm:"column:total_isi_angin" json:"total_isi_angin"`
	TotalCuciSteam         string    `gorm:"column:total_cuci_steam" json:"total_cuci_steam"`
	TotalTambalBan         string    `gorm:"column:total_tambal_ban" json:"total_tambal_ban"`
	TotalTransaksiTanpaBon string    `gorm:"column:total_transaksi_tanpa_bon" json:"total_transaksi_tanpa_bon"`
}

// TableName DailyExpensesArchive's table name
func (*DailyExpensesArchive) TableName() string {
	return TableNameDailyExpensesArchive
}
