// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameIncomeDiriver = "income_diriver"

// IncomeDiriver mapped from table <income_diriver>
type IncomeDiriver struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Status      int32     `gorm:"column:status" json:"status"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	DateIncome  string    `gorm:"column:date_income" json:"date_income"`
	FotoIncome  string    `gorm:"column:foto_income" json:"foto_income"`
	IDDriver    int32     `gorm:"column:id_driver" json:"id_driver"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
	ValueIncome string    `gorm:"column:value_income" json:"value_income"`
}

// TableName IncomeDiriver's table name
func (*IncomeDiriver) TableName() string {
	return TableNameIncomeDiriver
}
