// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameInvoiceModel = "invoice_models"

// InvoiceModel mapped from table <invoice_models>
type InvoiceModel struct {
	ID                  int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CompanyID           int32     `gorm:"column:company_id;not null" json:"company_id"`
	MonthTimestamp      int32     `gorm:"column:month_timestamp;not null" json:"month_timestamp"`
	PeriodYear          int32     `gorm:"column:period_year;not null" json:"period_year"`
	Periode             string    `gorm:"column:periode;not null" json:"periode"`
	IwoID               int32     `gorm:"column:iwo_id;not null" json:"iwo_id"`
	InvoiceNo           string    `gorm:"column:invoice_no" json:"invoice_no"`
	InvoiceNoB          string    `gorm:"column:invoice_no_b" json:"invoice_no_b"`
	InvoiceNoPpn        string    `gorm:"column:invoice_no_ppn" json:"invoice_no_ppn"`
	InvoiceAttn         string    `gorm:"column:invoice_attn" json:"invoice_attn"`
	InvoiceDate         string    `gorm:"column:invoice_date" json:"invoice_date"`
	TotalInvoiceValue   string    `gorm:"column:total_invoice_value;not null" json:"total_invoice_value"`
	TotalManagementFee  string    `gorm:"column:total_management_fee;not null" json:"total_management_fee"`
	Pph23               string    `gorm:"column:pph23;not null" json:"pph23"`
	Ppn                 string    `gorm:"column:ppn;not null" json:"ppn"`
	GrandTotalValueInvA string    `gorm:"column:grand_total_value_inv_A" json:"grand_total_value_inv_A"`
	GrandTotalValueInvB string    `gorm:"column:grand_total_value_inv_B" json:"grand_total_value_inv_B"`
	CreatedAt           time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt           time.Time `gorm:"column:updated_at" json:"updated_at"`
	CarRentalFee        string    `gorm:"column:car_rental_fee" json:"car_rental_fee"`
	InvoiceNoPo         string    `gorm:"column:invoice_no_po" json:"invoice_no_po"`
	OperationalCost     string    `gorm:"column:operational_cost" json:"operational_cost"`
	TotalCarRent        string    `gorm:"column:total_car_rent" json:"total_car_rent"`
	InvCover            string    `gorm:"column:inv_cover" json:"inv_cover"`
	InvCoverPpn         string    `gorm:"column:inv_cover_ppn" json:"inv_cover_ppn"`
	Summary             string    `gorm:"column:summary" json:"summary"`
	InvoiceNoC          string    `gorm:"column:invoice_no_c" json:"invoice_no_c"`
	IDUsers             int32     `gorm:"column:id_users" json:"id_users"`
	TypePpn             string    `gorm:"column:type_ppn" json:"type_ppn"`
	TglRentCar          string    `gorm:"column:tgl_rent_car" json:"tgl_rent_car"`
	PeriodeRentCar      string    `gorm:"column:periode_rent_car" json:"periode_rent_car"`
}

// TableName InvoiceModel's table name
func (*InvoiceModel) TableName() string {
	return TableNameInvoiceModel
}
