// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameIwoCarRental = "iwo_car_rentals"

// IwoCarRental mapped from table <iwo_car_rentals>
type IwoCarRental struct {
	ID           int32     `gorm:"column:id;primaryKey" json:"id"`
	CarRentalFee string    `gorm:"column:car_rental_fee" json:"car_rental_fee"`
	CarRentalTax string    `gorm:"column:car_rental_tax" json:"car_rental_tax"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName IwoCarRental's table name
func (*IwoCarRental) TableName() string {
	return TableNameIwoCarRental
}
