// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameIwoWorkday = "iwo_workdays"

// IwoWorkday mapped from table <iwo_workdays>
type IwoWorkday struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IwoTemplatesID    int32     `gorm:"column:iwo_templates_id;not null" json:"iwo_templates_id"`
	DayIndex          int32     `gorm:"column:day_index;not null;comment:1:senen|2:selasa|3:rabu|4:kamis|5:jumat|6:sabtu|7:minggu" json:"day_index"` // 1:senen|2:selasa|3:rabu|4:kamis|5:jumat|6:sabtu|7:minggu
	WorkHour          string    `gorm:"column:work_hour;not null" json:"work_hour"`
	LunchBreaktime    string    `gorm:"column:lunch_breaktime;not null" json:"lunch_breaktime"`
	DinnerBreaktime   string    `gorm:"column:dinner_breaktime" json:"dinner_breaktime"`
	IwoWorkdaysStatus int32     `gorm:"column:iwo_workdays_status;not null;comment:0:holiday|1:workday" json:"iwo_workdays_status"` // 0:holiday|1:workday
	CreatedAt         time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName IwoWorkday's table name
func (*IwoWorkday) TableName() string {
	return TableNameIwoWorkday
}
