// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameIwoTemplate = "iwo_templates"

// IwoTemplate mapped from table <iwo_templates>
type IwoTemplate struct {
	ID                         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IwoName                    string    `gorm:"column:iwo_name" json:"iwo_name"`
	DokumenAgreement           string    `gorm:"column:dokumen_agreement" json:"dokumen_agreement"`
	BasicSalary                string    `gorm:"column:basic_salary" json:"basic_salary"`
	AttendanceFeeID            int32     `gorm:"column:attendance_fee_id" json:"attendance_fee_id"`
	MonthlyAllowances          string    `gorm:"column:monthly_allowances" json:"monthly_allowances"`
	MedicalAllowances          string    `gorm:"column:medical_allowances" json:"medical_allowances"`
	BpjsEmploymentID           int32     `gorm:"column:bpjs_employment_id" json:"bpjs_employment_id"`
	BpjsMedicalID              int32     `gorm:"column:bpjs_medical_id" json:"bpjs_medical_id"`
	BpjsPensionID              int32     `gorm:"column:bpjs_pension_id" json:"bpjs_pension_id"`
	UniformFee                 string    `gorm:"column:uniform_fee" json:"uniform_fee"`
	ThrFeeID                   int32     `gorm:"column:thr_fee_id" json:"thr_fee_id"`
	IwoTemplateCreatorID       int32     `gorm:"column:iwo_template_creator_id" json:"iwo_template_creator_id"`
	EarlyMorning               string    `gorm:"column:early_morning" json:"early_morning"`
	BeforeTime                 string    `gorm:"column:before_time;default:05:00:00" json:"before_time"`
	LateNight                  string    `gorm:"column:late_night" json:"late_night"`
	AfterTime                  string    `gorm:"column:after_time;default:22:00:00" json:"after_time"`
	LateNight2                 string    `gorm:"column:late_night_2" json:"late_night_2"`
	AfterTime2                 string    `gorm:"column:after_time_2;default:23:00:00" json:"after_time_2"`
	CreatedAt                  time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt                  time.Time `gorm:"column:updated_at" json:"updated_at"`
	OvertimeWeekday            string    `gorm:"column:overtime_weekday" json:"overtime_weekday"`
	OvertimeWeekend            string    `gorm:"column:overtime_weekend" json:"overtime_weekend"`
	OutOfTownExclude           string    `gorm:"column:out_of_town_exclude" json:"out_of_town_exclude"`
	OutoftownRoundtrip         string    `gorm:"column:outoftown_roundtrip" json:"outoftown_roundtrip"`
	OutoftownOvernight         string    `gorm:"column:outoftown_overnight" json:"outoftown_overnight"`
	MasterCompaniesID          int32     `gorm:"column:master_companies_id" json:"master_companies_id"`
	Startdate                  string    `gorm:"column:startdate" json:"startdate"`
	Enddate                    string    `gorm:"column:enddate" json:"enddate"`
	TanggalGajian              int32     `gorm:"column:tanggal_gajian;comment:15" json:"tanggal_gajian"`                         // 15
	OvertimeType               string    `gorm:"column:overtime_type;default:flat;comment:flat or gradual" json:"overtime_type"` // flat or gradual
	CarRentalID                int32     `gorm:"column:car_rental_id" json:"car_rental_id"`
	NoHoliday                  string    `gorm:"column:no_holiday" json:"no_holiday"`
	Status                     int32     `gorm:"column:status;default:1" json:"status"`
	StatusPph23                int32     `gorm:"column:status_pph23;default:1;comment:if 0: false, 1: true" json:"status_pph23"` // if 0: false, 1: true
	AdminFee                   string    `gorm:"column:admin_fee" json:"admin_fee"`
	PayrollFee                 string    `gorm:"column:payroll_fee" json:"payroll_fee"`
	AddressIwo                 string    `gorm:"column:address_iwo" json:"address_iwo"`
	TglIwo                     string    `gorm:"column:tgl_iwo" json:"tgl_iwo"`
	Reff                       string    `gorm:"column:reff" json:"reff"`
	Npwp                       string    `gorm:"column:npwp" json:"npwp"`
	ReligiousHolidayAllowances string    `gorm:"column:religious_holiday_allowances" json:"religious_holiday_allowances"`
}

// TableName IwoTemplate's table name
func (*IwoTemplate) TableName() string {
	return TableNameIwoTemplate
}
