// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameListHoliday = "list_holidays"

// ListHoliday mapped from table <list_holidays>
type ListHoliday struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	HolidayDate   string    `gorm:"column:holiday_date;not null" json:"holiday_date"`
	HolidayNotes  string    `gorm:"column:holiday_notes;not null" json:"holiday_notes"`
	Status        int32     `gorm:"column:status;not null;default:1;comment:0:not active|1:active" json:"status"` // 0:not active|1:active
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
	Unixtimestamp int32     `gorm:"column:unixtimestamp;not null" json:"unixtimestamp"`
}

// TableName ListHoliday's table name
func (*ListHoliday) TableName() string {
	return TableNameListHoliday
}
