// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameManagementFee = "management_fees"

// ManagementFee mapped from table <management_fees>
type ManagementFee struct {
	ID                         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MfBasicSalary              string    `gorm:"column:mf_basic_salary;not null" json:"mf_basic_salary"`
	MfMonthlyAllowances        string    `gorm:"column:mf_monthly_allowances;not null" json:"mf_monthly_allowances"`
	MfOtherAllowances          string    `gorm:"column:mf_other_allowances;not null" json:"mf_other_allowances"`
	MfAttendanceFee            string    `gorm:"column:mf_attendance_fee;not null" json:"mf_attendance_fee"`
	MfOvertimeFee              string    `gorm:"column:mf_overtime_fee;not null" json:"mf_overtime_fee"`
	MfTransportationAllowances string    `gorm:"column:mf_transportation_allowances;not null" json:"mf_transportation_allowances"`
	MfOutOfTownAllowances      string    `gorm:"column:mf_out_of_town_allowances;not null" json:"mf_out_of_town_allowances"`
	MfOperationalCost          string    `gorm:"column:mf_operational_cost;not null" json:"mf_operational_cost"`
	CreatedAt                  time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt                  time.Time `gorm:"column:updated_at" json:"updated_at"`
	IDIwo                      int32     `gorm:"column:id_iwo" json:"id_iwo"`
	IDIwoNsr                   int32     `gorm:"column:id_iwo_nsr" json:"id_iwo_nsr"`
}

// TableName ManagementFee's table name
func (*ManagementFee) TableName() string {
	return TableNameManagementFee
}
