// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameMasterCompany = "master_companies"

// MasterCompany mapped from table <master_companies>
type MasterCompany struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CompanyName       string    `gorm:"column:company_name;not null" json:"company_name"`
	CompanyAddress    string    `gorm:"column:company_address;not null" json:"company_address"`
	CompanyGaID       int32     `gorm:"column:company_ga_id" json:"company_ga_id"`
	CompanyCreatorID  int32     `gorm:"column:company_creator_id;not null" json:"company_creator_id"`
	AddressAreaID     int32     `gorm:"column:address_area_id" json:"address_area_id"`
	CreatedAt         time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at" json:"updated_at"`
	TypeInvoice       string    `gorm:"column:type_invoice;comment:0:default|1:split" json:"type_invoice"` // 0:default|1:split
	CompanyPhone      string    `gorm:"column:company_phone;not null;default:0" json:"company_phone"`
	InternalCompanyID string    `gorm:"column:internal_company_id;not null;default:1" json:"internal_company_id"`
	Status            int32     `gorm:"column:status;not null;default:1" json:"status"`
	TypePpn           int32     `gorm:"column:type_ppn" json:"type_ppn"`
	TypePph23         int32     `gorm:"column:type_pph23" json:"type_pph23"`
	Npwp              string    `gorm:"column:npwp" json:"npwp"`
	Reff              string    `gorm:"column:reff" json:"reff"`
	CodeCustomer      string    `gorm:"column:code_customer" json:"code_customer"`
	TypeSlipGaji      int32     `gorm:"column:type_slip_gaji" json:"type_slip_gaji"`
}

// TableName MasterCompany's table name
func (*MasterCompany) TableName() string {
	return TableNameMasterCompany
}
