// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameSalaryArchiveEmployee = "salary_archive_employees"

// SalaryArchiveEmployee mapped from table <salary_archive_employees>
type SalaryArchiveEmployee struct {
	ID                                   int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CompanyID                            int32     `gorm:"column:company_id;not null" json:"company_id"`
	ServiceDriversID                     int32     `gorm:"column:service_drivers_id;not null" json:"service_drivers_id"`
	InternalCompanyID                    int32     `gorm:"column:internal_company_id;not null" json:"internal_company_id"`
	IwoID                                int32     `gorm:"column:iwo_id;not null" json:"iwo_id"`
	MonthTimestamp                       int32     `gorm:"column:month_timestamp" json:"month_timestamp"`
	Periode                              string    `gorm:"column:periode" json:"periode"`
	InvoiceNo                            string    `gorm:"column:invoice_no" json:"invoice_no"`
	BasicSalary                          string    `gorm:"column:basic_salary" json:"basic_salary"`
	MonthlyAllowance                     string    `gorm:"column:monthly_allowance" json:"monthly_allowance"`
	OtherAllowance                       string    `gorm:"column:other_allowance" json:"other_allowance"`
	Uniform                              string    `gorm:"column:uniform;not null;default:0" json:"uniform"`
	BpjsTkEmployee                       string    `gorm:"column:bpjs_tk_employee;not null;default:0" json:"bpjs_tk_employee"`
	BpjsTk                               string    `gorm:"column:bpjs_tk;not null;default:0" json:"bpjs_tk"`
	BpjsKesEmployee                      string    `gorm:"column:bpjs_kes_employee;not null;default:0" json:"bpjs_kes_employee"`
	BpjsKes                              string    `gorm:"column:bpjs_kes;not null;default:0" json:"bpjs_kes"`
	BpjsDpEmployee                       string    `gorm:"column:bpjs_dp_employee;not null;default:0" json:"bpjs_dp_employee"`
	BpjsDp                               string    `gorm:"column:bpjs_dp;not null;default:0" json:"bpjs_dp"`
	AttNumber                            string    `gorm:"column:att_number;not null;default:0" json:"att_number"`
	AttValue                             string    `gorm:"column:att_value;not null;default:0" json:"att_value"`
	AttType                              string    `gorm:"column:att_type;not null;default:0" json:"att_type"`
	OtNormNumber                         string    `gorm:"column:ot_norm_number;not null;default:0" json:"ot_norm_number"`
	OtNormValue                          string    `gorm:"column:ot_norm_value;not null;default:0" json:"ot_norm_value"`
	OtHolNumber                          string    `gorm:"column:ot_hol_number;not null;default:0" json:"ot_hol_number"`
	OtHolValue                           string    `gorm:"column:ot_hol_value;not null;default:0" json:"ot_hol_value"`
	TransNumber                          string    `gorm:"column:trans_number;not null;default:0" json:"trans_number"`
	TransValue                           string    `gorm:"column:trans_value" json:"trans_value"`
	OutTownNumber                        string    `gorm:"column:out_town_number;not null;default:0" json:"out_town_number"`
	OutTownValue                         string    `gorm:"column:out_town_value;not null;default:0" json:"out_town_value"`
	OutOverNumber                        string    `gorm:"column:out_over_number;not null;default:0" json:"out_over_number"`
	OutOverValue                         string    `gorm:"column:out_over_value;not null;default:0" json:"out_over_value"`
	AgentFee                             string    `gorm:"column:agent_fee;not null;default:0" json:"agent_fee"`
	PresentaseAgentFee                   string    `gorm:"column:presentase_agent_fee;not null;default:0" json:"presentase_agent_fee"`
	PayrollFee                           string    `gorm:"column:payroll_fee" json:"payroll_fee"`
	BiayaAdministrasi                    string    `gorm:"column:biaya_administrasi;not null;default:0" json:"biaya_administrasi"`
	Pph21                                string    `gorm:"column:pph21;not null;default:0" json:"pph21"`
	KekuranganGaji                       string    `gorm:"column:kekurangan_gaji;not null;default:0" json:"kekurangan_gaji"`
	KelebihanGaji                        string    `gorm:"column:kelebihan_gaji;not null;default:0" json:"kelebihan_gaji"`
	Workday                              int32     `gorm:"column:workday;not null" json:"workday"`
	EmployeeWorkday                      string    `gorm:"column:employee_workday" json:"employee_workday"`
	SalaryDetailJSON                     string    `gorm:"column:salary_detail_json;not null" json:"salary_detail_json"`
	CreatedAt                            time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt                            time.Time `gorm:"column:updated_at" json:"updated_at"`
	PeriodYear                           int32     `gorm:"column:period_year;default:2018" json:"period_year"`
	TunjanganPensiunNonBpjs              string    `gorm:"column:tunjangan_pensiun_non_bpjs;not null;default:0" json:"tunjangan_pensiun_non_bpjs"`
	TunjanganKesehatanNonBpjs            string    `gorm:"column:tunjangan_kesehatan_non_bpjs;not null;default:0" json:"tunjangan_kesehatan_non_bpjs"`
	TotalPenerimaan                      string    `gorm:"column:total_penerimaan;not null;default:0" json:"total_penerimaan"`
	TotalPotongan                        string    `gorm:"column:total_potongan;not null;default:0" json:"total_potongan"`
	GajiBersih                           string    `gorm:"column:gaji_bersih;not null;default:0" json:"gaji_bersih"`
	TotalGajiBersih                      string    `gorm:"column:total_gaji_bersih;not null;default:0" json:"total_gaji_bersih"`
	TulisanNpwp                          string    `gorm:"column:tulisan_npwp;not null;default:0" json:"tulisan_npwp"`
	JobholderID                          int32     `gorm:"column:jobholder_id;not null" json:"jobholder_id"`
	DriverStatus                         int32     `gorm:"column:driver_status;not null;comment:100:job holder | 200: replacement" json:"driver_status"` // 100:job holder | 200: replacement
	SalaryArchiveID                      int32     `gorm:"column:salary_archive_id;not null" json:"salary_archive_id"`
	TotalForCalculation                  string    `gorm:"column:total_for_calculation;not null;default:0" json:"total_for_calculation"`
	SalaryDate                           int32     `gorm:"column:salary_date;not null" json:"salary_date"`
	MfBasicSalaryPercentage              string    `gorm:"column:mf_basic_salary_percentage;not null;default:0" json:"mf_basic_salary_percentage"`
	MfBasicSalaryValue                   string    `gorm:"column:mf_basic_salary_value;not null;default:0" json:"mf_basic_salary_value"`
	MfMonthlyAllowancesFeesPercentage    string    `gorm:"column:mf_monthly_allowances_fees_percentage;not null;default:0" json:"mf_monthly_allowances_fees_percentage"`
	MfMonthlyAllowancesFeesValue         string    `gorm:"column:mf_monthly_allowances_fees_value;not null;default:0" json:"mf_monthly_allowances_fees_value"`
	MfOtherAllowancesFeesPercentage      string    `gorm:"column:mf_other_allowances_fees_percentage;not null;default:0" json:"mf_other_allowances_fees_percentage"`
	MfOtherAllowancesFeesValue           string    `gorm:"column:mf_other_allowances_fees_value;not null;default:0" json:"mf_other_allowances_fees_value"`
	MfAttendanceFeesPercentage           string    `gorm:"column:mf_attendance_fees_percentage;not null;default:0" json:"mf_attendance_fees_percentage"`
	MfAttendanceFeesValue                string    `gorm:"column:mf_attendance_fees_value;not null;default:0" json:"mf_attendance_fees_value"`
	MfOvertimeFeesPercentage             string    `gorm:"column:mf_overtime_fees_percentage;not null;default:0" json:"mf_overtime_fees_percentage"`
	MfOvertimeFeesValue                  string    `gorm:"column:mf_overtime_fees_value;not null;default:0" json:"mf_overtime_fees_value"`
	MfTransportAllowancesFeesPercentage  string    `gorm:"column:mf_transport_allowances_fees_percentage;not null;default:0" json:"mf_transport_allowances_fees_percentage"`
	MfTransportAllowancesFeesValue       string    `gorm:"column:mf_transport_allowances_fees_value;not null;default:0" json:"mf_transport_allowances_fees_value"`
	MfOutoftownAllowancesFeesPercentage  string    `gorm:"column:mf_outoftown_allowances_fees_percentage;not null;default:0" json:"mf_outoftown_allowances_fees_percentage"`
	MfOutoftownAllowancesFeesValue       string    `gorm:"column:mf_outoftown_allowances_fees_value;not null;default:0" json:"mf_outoftown_allowances_fees_value"`
	MfOperationalCostFeesPercentage      string    `gorm:"column:mf_operational_cost_fees_percentage;not null;default:0" json:"mf_operational_cost_fees_percentage"`
	MfOperationalCostAllowancesFeesValue string    `gorm:"column:mf_operational_cost_allowances_fees_value;not null;default:0" json:"mf_operational_cost_allowances_fees_value"`
	IDUsers                              int32     `gorm:"column:id_users" json:"id_users"`
	StatusData                           int32     `gorm:"column:status_data" json:"status_data"`
	Thr20242025                          string    `gorm:"column:thr_2024_2025" json:"thr_2024_2025"`
	Uuck                                 string    `gorm:"column:uuck" json:"uuck"`
	TotalJamLemburWeekdays               string    `gorm:"column:total_jam_lembur_weekdays" json:"total_jam_lembur_weekdays"`
	TotalJamLemburHolidays               string    `gorm:"column:total_jam_lembur_holidays" json:"total_jam_lembur_holidays"`
	TotalJamOvertime                     string    `gorm:"column:total_jam_overtime" json:"total_jam_overtime"`
	StatusDriver                         string    `gorm:"column:status_driver" json:"status_driver"`
	StatusPublish                        int32     `gorm:"column:status_publish" json:"status_publish"`
	TglGajiDriver                        string    `gorm:"column:tgl_gaji_driver" json:"tgl_gaji_driver"`
}

// TableName SalaryArchiveEmployee's table name
func (*SalaryArchiveEmployee) TableName() string {
	return TableNameSalaryArchiveEmployee
}
