// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameSalaryArchiveDriver = "salary_archive_drivers"

// SalaryArchiveDriver mapped from table <salary_archive_drivers>
type SalaryArchiveDriver struct {
	ID                                   int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CompanyID                            int32     `gorm:"column:company_id;not null" json:"company_id"`
	ServiceDriversID                     int32     `gorm:"column:service_drivers_id;not null" json:"service_drivers_id"`
	InternalCompanyID                    int32     `gorm:"column:internal_company_id;not null" json:"internal_company_id"`
	MonthTimestamp                       int64     `gorm:"column:month_timestamp" json:"month_timestamp"`
	Periode                              string    `gorm:"column:periode" json:"periode"`
	InvoiceNo                            string    `gorm:"column:invoice_no" json:"invoice_no"`
	InvoiceNoPpn                         string    `gorm:"column:invoice_no_ppn" json:"invoice_no_ppn"`
	InvoiceDate                          string    `gorm:"column:invoice_date" json:"invoice_date"`
	BasicSalary                          string    `gorm:"column:basic_salary" json:"basic_salary"`
	MonthlyAllowance                     string    `gorm:"column:monthly_allowance" json:"monthly_allowance"`
	OtherAllowance                       string    `gorm:"column:other_allowance" json:"other_allowance"`
	Uniform                              string    `gorm:"column:uniform" json:"uniform"`
	BpjsTk                               string    `gorm:"column:bpjs_tk" json:"bpjs_tk"`
	BpjsTkEmployee                       string    `gorm:"column:bpjs_tk_employee" json:"bpjs_tk_employee"`
	BpjsKes                              string    `gorm:"column:bpjs_kes" json:"bpjs_kes"`
	BpjsKesEmployee                      string    `gorm:"column:bpjs_kes_employee" json:"bpjs_kes_employee"`
	BpjsDp                               string    `gorm:"column:bpjs_dp" json:"bpjs_dp"`
	BpjsDpEmployee                       string    `gorm:"column:bpjs_dp_employee" json:"bpjs_dp_employee"`
	AttNumber                            string    `gorm:"column:att_number" json:"att_number"`
	AttValue                             string    `gorm:"column:att_value" json:"att_value"`
	AttType                              string    `gorm:"column:att_type" json:"att_type"`
	OtNormNumber                         string    `gorm:"column:ot_norm_number" json:"ot_norm_number"`
	OtNormValue                          string    `gorm:"column:ot_norm_value" json:"ot_norm_value"`
	OtHolNumber                          string    `gorm:"column:ot_hol_number" json:"ot_hol_number"`
	OtHolValue                           string    `gorm:"column:ot_hol_value" json:"ot_hol_value"`
	TransNumber                          string    `gorm:"column:trans_number" json:"trans_number"`
	TransValue                           string    `gorm:"column:trans_value" json:"trans_value"`
	OutTownNumber                        string    `gorm:"column:out_town_number" json:"out_town_number"`
	OutTownValue                         string    `gorm:"column:out_town_value" json:"out_town_value"`
	OutOverNumber                        string    `gorm:"column:out_over_number" json:"out_over_number"`
	OutOverValue                         string    `gorm:"column:out_over_value" json:"out_over_value"`
	AgentFee                             string    `gorm:"column:agent_fee" json:"agent_fee"`
	PresentaseAgentFee                   string    `gorm:"column:presentase_agent_fee" json:"presentase_agent_fee"`
	PayrollFee                           string    `gorm:"column:payroll_fee" json:"payroll_fee"`
	BiayaAdministrasi                    string    `gorm:"column:biaya_administrasi" json:"biaya_administrasi"`
	Pph23                                string    `gorm:"column:pph23" json:"pph23"`
	Pph21                                string    `gorm:"column:pph21" json:"pph21"`
	Ppn                                  string    `gorm:"column:ppn" json:"ppn"`
	KekuranganGaji                       string    `gorm:"column:kekurangan_gaji" json:"kekurangan_gaji"`
	KelebihanGaji                        string    `gorm:"column:kelebihan_gaji" json:"kelebihan_gaji"`
	SalaryDetailJSON                     string    `gorm:"column:salary_detail_json" json:"salary_detail_json"`
	CreatedAt                            time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt                            time.Time `gorm:"column:updated_at" json:"updated_at"`
	Workday                              int32     `gorm:"column:workday" json:"workday"`
	IwoID                                int32     `gorm:"column:iwo_id" json:"iwo_id"`
	YearlyAllowance                      string    `gorm:"column:yearly_allowance" json:"yearly_allowance"`
	MonthlyThr                           string    `gorm:"column:monthly_thr" json:"monthly_thr"`
	EarlyMorning                         string    `gorm:"column:early_morning" json:"early_morning"`
	LateNight                            string    `gorm:"column:late_night" json:"late_night"`
	PeriodYear                           int32     `gorm:"column:period_year;default:2018" json:"period_year"`
	AttnInvoice                          string    `gorm:"column:attn_invoice" json:"attn_invoice"`
	CarRentFee                           string    `gorm:"column:car_rent_fee" json:"car_rent_fee"`
	MfBasicSalaryPercentage              string    `gorm:"column:mf_basic_salary_percentage" json:"mf_basic_salary_percentage"`
	MfBasicSalaryValue                   string    `gorm:"column:mf_basic_salary_value" json:"mf_basic_salary_value"`
	MfMonthlyAllowancesFeesPercentage    string    `gorm:"column:mf_monthly_allowances_fees_percentage" json:"mf_monthly_allowances_fees_percentage"`
	MfMonthlyAllowancesFeesValue         string    `gorm:"column:mf_monthly_allowances_fees_value" json:"mf_monthly_allowances_fees_value"`
	MfOtherAllowancesFeesPercentage      string    `gorm:"column:mf_other_allowances_fees_percentage" json:"mf_other_allowances_fees_percentage"`
	MfOtherAllowancesFeesValue           string    `gorm:"column:mf_other_allowances_fees_value" json:"mf_other_allowances_fees_value"`
	MfAttendanceFeesPercentage           string    `gorm:"column:mf_attendance_fees_percentage" json:"mf_attendance_fees_percentage"`
	MfAttendanceFeesValue                string    `gorm:"column:mf_attendance_fees_value" json:"mf_attendance_fees_value"`
	MfOvertimeFeesPercentage             string    `gorm:"column:mf_overtime_fees_percentage" json:"mf_overtime_fees_percentage"`
	MfOvertimeFeesValue                  string    `gorm:"column:mf_overtime_fees_value" json:"mf_overtime_fees_value"`
	MfTransportAllowancesFeesPercentage  string    `gorm:"column:mf_transport_allowances_fees_percentage" json:"mf_transport_allowances_fees_percentage"`
	MfTransportAllowancesFeesValue       string    `gorm:"column:mf_transport_allowances_fees_value" json:"mf_transport_allowances_fees_value"`
	MfOutoftownAllowancesFeesPercentage  string    `gorm:"column:mf_outoftown_allowances_fees_percentage" json:"mf_outoftown_allowances_fees_percentage"`
	MfOutoftownAllowancesFeesValue       string    `gorm:"column:mf_outoftown_allowances_fees_value" json:"mf_outoftown_allowances_fees_value"`
	MfOperationalCostFeesPercentage      string    `gorm:"column:mf_operational_cost_fees_percentage" json:"mf_operational_cost_fees_percentage"`
	MfOperationalCostAllowancesFeesValue string    `gorm:"column:mf_operational_cost_allowances_fees_value" json:"mf_operational_cost_allowances_fees_value"`
	InvoiceNoB                           string    `gorm:"column:invoice_no_b" json:"invoice_no_b"`
	OperationalCost                      string    `gorm:"column:operational_cost" json:"operational_cost"`
	JasaTransportationService            string    `gorm:"column:jasa_transportation_service" json:"jasa_transportation_service"`
	OrderbyPrint                         string    `gorm:"column:orderby_print" json:"orderby_print"`
	PoliceNumber                         string    `gorm:"column:police_number" json:"police_number"`
	TypeUnit                             string    `gorm:"column:type_unit" json:"type_unit"`
	UserName                             string    `gorm:"column:user_name" json:"user_name"`
	CarRent                              string    `gorm:"column:car_rent" json:"car_rent"`
	MealAllowances                       string    `gorm:"column:meal_allowances" json:"meal_allowances"`
	NightShiftAllowance                  string    `gorm:"column:night_shift_allowance" json:"night_shift_allowance"`
	PercentPph21                         string    `gorm:"column:percent_pph21" json:"percent_pph21"`
	CategoryTer                          string    `gorm:"column:category_ter" json:"category_ter"`
	InvoiceMobil                         string    `gorm:"column:invoice_mobil" json:"invoice_mobil"`
	InvoiceNoC                           string    `gorm:"column:invoice_no_c" json:"invoice_no_c"`
	IDUsers                              int32     `gorm:"column:id_users" json:"id_users"`
	Uuck                                 string    `gorm:"column:uuck" json:"uuck"`
	TotalJamLemburWeekdays               string    `gorm:"column:total_jam_lembur_weekdays" json:"total_jam_lembur_weekdays"`
	TotalJamLemburHolidays               string    `gorm:"column:total_jam_lembur_holidays" json:"total_jam_lembur_holidays"`
	TotalJamOvertime                     string    `gorm:"column:total_jam_overtime" json:"total_jam_overtime"`
	StatusDriver                         string    `gorm:"column:status_driver" json:"status_driver"`
	DriverInvoice                        string    `gorm:"column:driver_invoice" json:"driver_invoice"`
	Kompensasi                           string    `gorm:"column:kompensasi" json:"kompensasi"`
}

// TableName SalaryArchiveDriver's table name
func (*SalaryArchiveDriver) TableName() string {
	return TableNameSalaryArchiveDriver
}
