// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameSalaryCutOff = "salary_cut_offs"

// SalaryCutOff mapped from table <salary_cut_offs>
type SalaryCutOff struct {
	ID          int32     `gorm:"column:id;primaryKey" json:"id"`
	SalaryDate  int32     `gorm:"column:salary_date" json:"salary_date"`
	CutoffStart int32     `gorm:"column:cutoff_start" json:"cutoff_start"`
	CutoffStop  int32     `gorm:"column:cutoff_stop" json:"cutoff_stop"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName SalaryCutOff's table name
func (*SalaryCutOff) TableName() string {
	return TableNameSalaryCutOff
}
