// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameServiceDriver = "service_drivers"

// ServiceDriver mapped from table <service_drivers>
type ServiceDriver struct {
	ID                  int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IDRecruitment       int32     `gorm:"column:id_recruitment" json:"id_recruitment"`
	FullName            string    `gorm:"column:full_name;not null" json:"full_name"`
	PhoneNumber         string    `gorm:"column:phone_number;not null" json:"phone_number"`
	HomeAddress         string    `gorm:"column:home_address;not null" json:"home_address"`
	Photo               string    `gorm:"column:photo" json:"photo"`
	DokumenPkwt         string    `gorm:"column:dokumen_pkwt" json:"dokumen_pkwt"`
	CreatedAt           time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt           time.Time `gorm:"column:updated_at" json:"updated_at"`
	EmployeeID          string    `gorm:"column:employee_id" json:"employee_id"`
	AddressAreaID       string    `gorm:"column:address_area_id" json:"address_area_id"`
	NoBerkas            string    `gorm:"column:no_berkas" json:"no_berkas"`
	NoKtp               string    `gorm:"column:no_ktp" json:"no_ktp"`
	NoNpwp              string    `gorm:"column:no_npwp" json:"no_npwp"`
	Religion            string    `gorm:"column:religion" json:"religion"`
	Birthdate           string    `gorm:"column:birthdate" json:"birthdate"`
	KtpAddress          string    `gorm:"column:ktp_address" json:"ktp_address"`
	JobTitle            int32     `gorm:"column:job_title;not null;default:1;comment:1:driver|2:office boy|3:helper|4:collector|5:tea server" json:"job_title"` // 1:driver|2:office boy|3:helper|4:collector|5:tea server
	NoRekening          string    `gorm:"column:no_rekening" json:"no_rekening"`
	NamaRekening        string    `gorm:"column:nama_rekening" json:"nama_rekening"`
	NamaBank            string    `gorm:"column:nama_bank" json:"nama_bank"`
	Status              int32     `gorm:"column:status;not null;default:1;comment:0:not active|1:active" json:"status"` // 0:not active|1:active
	PhoneNumber2        string    `gorm:"column:phone_number2;not null;default:0" json:"phone_number2"`
	PhoneNumber3        string    `gorm:"column:phone_number3;not null;default:0" json:"phone_number3"`
	StatusBpjsPensiun   int32     `gorm:"column:status_bpjs_pensiun;not null;default:1;comment:Type 1:client&driver | Type 2:client&driver cash | Type 3:no client&driver" json:"status_bpjs_pensiun"`     // Type 1:client&driver | Type 2:client&driver cash | Type 3:no client&driver
	StatusBpjsKesehatan int32     `gorm:"column:status_bpjs_kesehatan;not null;default:1;comment:Type 1:client&driver | Type 2:client&driver cash | Type 3:no client&driver" json:"status_bpjs_kesehatan"` // Type 1:client&driver | Type 2:client&driver cash | Type 3:no client&driver
	CategoryTer         string    `gorm:"column:category_ter" json:"category_ter"`
	StatusDriver        string    `gorm:"column:status_driver" json:"status_driver"`
	CategoryTerNew      string    `gorm:"column:category_ter_new" json:"category_ter_new"`
}

// TableName ServiceDriver's table name
func (*ServiceDriver) TableName() string {
	return TableNameServiceDriver
}
