// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameServiceDetail = "service_details"

// ServiceDetail mapped from table <service_details>
type ServiceDetail struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ServiceUsersID   int32     `gorm:"column:service_users_id;not null" json:"service_users_id"`
	ServiceDriversID int32     `gorm:"column:service_drivers_id;not null" json:"service_drivers_id"`
	ServiceStatus    int32     `gorm:"column:service_status;not null;comment:0:not active|1:active|2:suspend" json:"service_status"` // 0:not active|1:active|2:suspend
	CreatedAt        time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at" json:"updated_at"`
	TanggalMasuk     string    `gorm:"column:tanggal_masuk" json:"tanggal_masuk"`
	StatusDriver     string    `gorm:"column:status_driver" json:"status_driver"`
}

// TableName ServiceDetail's table name
func (*ServiceDetail) TableName() string {
	return TableNameServiceDetail
}
