// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameServiceReplacement = "service_replacements"

// ServiceReplacement mapped from table <service_replacements>
type ServiceReplacement struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ServiceDetailsID int32     `gorm:"column:service_details_id;not null" json:"service_details_id"`
	StartDate        string    `gorm:"column:start_date;not null" json:"start_date"`
	EndDate          string    `gorm:"column:end_date;not null" json:"end_date"`
	Reason           string    `gorm:"column:reason" json:"reason"`
	ServiceDriversID int32     `gorm:"column:service_drivers_id;not null" json:"service_drivers_id"`
	CreatedAt        time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at" json:"updated_at"`
	TypeReplacement  int32     `gorm:"column:type_replacement;not null;comment:0:temporary|1:permanent" json:"type_replacement"` // 0:temporary|1:permanent
	Status           int32     `gorm:"column:status;default:1" json:"status"`
	DriverPengganti  string    `gorm:"column:driver_pengganti" json:"driver_pengganti"`
	Nopol            string    `gorm:"column:nopol" json:"nopol"`
	JenisMobil       string    `gorm:"column:jenis_mobil" json:"jenis_mobil"`
	WarnaMobil       string    `gorm:"column:warna_mobil" json:"warna_mobil"`
	KetLokasiParkir  string    `gorm:"column:ket_lokasi_parkir" json:"ket_lokasi_parkir"`
	FrontPhoto       string    `gorm:"column:front_photo" json:"front_photo"`
}

// TableName ServiceReplacement's table name
func (*ServiceReplacement) TableName() string {
	return TableNameServiceReplacement
}
