// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameServiceDriversBackup = "service_drivers_backup"

// ServiceDriversBackup mapped from table <service_drivers_backup>
type ServiceDriversBackup struct {
	ID                  int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FullName            string    `gorm:"column:full_name" json:"full_name"`
	PhoneNumber         string    `gorm:"column:phone_number" json:"phone_number"`
	HomeAddress         string    `gorm:"column:home_address" json:"home_address"`
	Photo               string    `gorm:"column:photo" json:"photo"`
	DokumenPkwt         string    `gorm:"column:dokumen_pkwt" json:"dokumen_pkwt"`
	CreatedAt           time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt           time.Time `gorm:"column:updated_at" json:"updated_at"`
	EmployeeID          string    `gorm:"column:employee_id" json:"employee_id"`
	AddressAreaID       int32     `gorm:"column:address_area_id" json:"address_area_id"`
	NoBerkas            string    `gorm:"column:no_berkas" json:"no_berkas"`
	NoKtp               string    `gorm:"column:no_ktp" json:"no_ktp"`
	NoNpwp              string    `gorm:"column:no_npwp" json:"no_npwp"`
	Religion            string    `gorm:"column:religion" json:"religion"`
	Birthdate           string    `gorm:"column:birthdate" json:"birthdate"`
	KtpAddress          string    `gorm:"column:ktp_address" json:"ktp_address"`
	JobTitle            int32     `gorm:"column:job_title;default:1;comment:1:driver|2:office boy|3:helper|4:collector|5:tea server" json:"job_title"` // 1:driver|2:office boy|3:helper|4:collector|5:tea server
	NoRekening          string    `gorm:"column:no_rekening" json:"no_rekening"`
	NamaRekening        string    `gorm:"column:nama_rekening" json:"nama_rekening"`
	NamaBank            string    `gorm:"column:nama_bank" json:"nama_bank"`
	Status              int32     `gorm:"column:status;default:1;comment:0:not active|1:active" json:"status"` // 0:not active|1:active
	PhoneNumber2        string    `gorm:"column:phone_number2" json:"phone_number2"`
	PhoneNumber3        string    `gorm:"column:phone_number3" json:"phone_number3"`
	StatusBpjsPensiun   int32     `gorm:"column:status_bpjs_pensiun;default:1;comment:Type 1:client&driver | Type 2:client&driver cash | Type 3:no client&driver" json:"status_bpjs_pensiun"`     // Type 1:client&driver | Type 2:client&driver cash | Type 3:no client&driver
	StatusBpjsKesehatan int32     `gorm:"column:status_bpjs_kesehatan;default:1;comment:Type 1:client&driver | Type 2:client&driver cash | Type 3:no client&driver" json:"status_bpjs_kesehatan"` // Type 1:client&driver | Type 2:client&driver cash | Type 3:no client&driver
	CategoryTer         string    `gorm:"column:category_ter" json:"category_ter"`
	StatusDriver        string    `gorm:"column:status_driver" json:"status_driver"`
	CategoryTerNew      string    `gorm:"column:category_ter_new" json:"category_ter_new"`
	IDServiceDrivers    int32     `gorm:"column:id_service_drivers" json:"id_service_drivers"`
}

// TableName ServiceDriversBackup's table name
func (*ServiceDriversBackup) TableName() string {
	return TableNameServiceDriversBackup
}
