// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameServiceUsersDaily = "service_users_daily"

// ServiceUsersDaily mapped from table <service_users_daily>
type ServiceUsersDaily struct {
	IDUsersDaily      int32     `gorm:"column:id_users_daily;primaryKey;autoIncrement:true" json:"id_users_daily"`
	Email             string    `gorm:"column:email" json:"email"`
	Status            int32     `gorm:"column:status;default:1" json:"status"`
	CreatedAt         time.Time `gorm:"column:created_at" json:"created_at"`
	FullName          string    `gorm:"column:full_name" json:"full_name"`
	HomeAddress       string    `gorm:"column:home_address" json:"home_address"`
	IwoTemplatesID    int32     `gorm:"column:iwo_templates_id" json:"iwo_templates_id"`
	MasterCompaniesID int32     `gorm:"column:master_companies_id" json:"master_companies_id"`
	PhoneNumber       string    `gorm:"column:phone_number" json:"phone_number"`
	UpdatedAt         time.Time `gorm:"column:updated_at" json:"updated_at"`
	WorkAddress       string    `gorm:"column:work_address" json:"work_address"`
}

// TableName ServiceUsersDaily's table name
func (*ServiceUsersDaily) TableName() string {
	return TableNameServiceUsersDaily
}
