// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameServiceUser = "service_users"

// ServiceUser mapped from table <service_users>
type ServiceUser struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MasterCompaniesID int32     `gorm:"column:master_companies_id;not null" json:"master_companies_id"`
	IwoTemplatesID    int32     `gorm:"column:iwo_templates_id;not null" json:"iwo_templates_id"`
	FullName          string    `gorm:"column:full_name;not null" json:"full_name"`
	HomeAddress       string    `gorm:"column:home_address;not null" json:"home_address"`
	WorkAddress       string    `gorm:"column:work_address;not null" json:"work_address"`
	Email             string    `gorm:"column:email" json:"email"`
	PhoneNumber       string    `gorm:"column:phone_number" json:"phone_number"`
	CreatedAt         time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at" json:"updated_at"`
	Status            int32     `gorm:"column:status" json:"status"`
}

// TableName ServiceUser's table name
func (*ServiceUser) TableName() string {
	return TableNameServiceUser
}
