// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTbActivity = "tb_activity"

// TbActivity mapped from table <tb_activity>
type TbActivity struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TimesheetID   string    `gorm:"column:timesheet_id" json:"timesheet_id"`
	Lat           string    `gorm:"column:lat" json:"lat"`
	Long          string    `gorm:"column:long" json:"long"`
	FotoAktifitas string    `gorm:"column:foto_aktifitas" json:"foto_aktifitas"`
	StartVisit    string    `gorm:"column:start_visit" json:"start_visit"`
	EndVisit      string    `gorm:"column:end_visit" json:"end_visit"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
	Status        int32     `gorm:"column:status" json:"status"`
}

// TableName TbActivity's table name
func (*TbActivity) TableName() string {
	return TableNameTbActivity
}
