// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTbCustomInvoiceMaster = "tb_custom_invoice_master"

// TbCustomInvoiceMaster mapped from table <tb_custom_invoice_master>
type TbCustomInvoiceMaster struct {
	ID                  int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CustomerInvoiceName string    `gorm:"column:customer_invoice_name" json:"customer_invoice_name"`
	CompanyName         string    `gorm:"column:company_name" json:"company_name"`
	CompanyAddress      string    `gorm:"column:company_address" json:"company_address"`
	GaName              string    `gorm:"column:ga_name" json:"ga_name"`
	InternalCompanyID   int32     `gorm:"column:internal_company_id" json:"internal_company_id"`
	TypeInvoice         int32     `gorm:"column:type_invoice" json:"type_invoice"`
	TypePpn             int32     `gorm:"column:type_ppn" json:"type_ppn"`
	TypePph23           int32     `gorm:"column:type_pph23" json:"type_pph23"`
	Status              int32     `gorm:"column:status;default:1" json:"status"`
	CreatedAt           time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt           time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName TbCustomInvoiceMaster's table name
func (*TbCustomInvoiceMaster) TableName() string {
	return TableNameTbCustomInvoiceMaster
}
