// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTbCustomInvoiceModel = "tb_custom_invoice_model"

// TbCustomInvoiceModel mapped from table <tb_custom_invoice_model>
type TbCustomInvoiceModel struct {
	ID                     int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MonthTimestamp         int32     `gorm:"column:month_timestamp" json:"month_timestamp"`
	PeriodYear             int32     `gorm:"column:period_year" json:"period_year"`
	Periode                string    `gorm:"column:periode" json:"periode"`
	IDCustomeInvoiceMaster int32     `gorm:"column:id_custome_invoice_master" json:"id_custome_invoice_master"`
	InvoiceNo              string    `gorm:"column:invoice_no" json:"invoice_no"`
	InvoiceNoB             string    `gorm:"column:invoice_no_b" json:"invoice_no_b"`
	InvoiceNoC             string    `gorm:"column:invoice_no_c" json:"invoice_no_c"`
	InvoiceNoPpn           string    `gorm:"column:invoice_no_ppn" json:"invoice_no_ppn"`
	InvoiceNoPo            string    `gorm:"column:invoice_no_po" json:"invoice_no_po"`
	InvoiceAttn            string    `gorm:"column:invoice_attn" json:"invoice_attn"`
	InvoiceDate            string    `gorm:"column:invoice_date" json:"invoice_date"`
	TotalInvoiceValue      int32     `gorm:"column:total_invoice_value" json:"total_invoice_value"`
	TotalManagementFee     int32     `gorm:"column:total_management_fee" json:"total_management_fee"`
	Pph23                  int32     `gorm:"column:pph_23" json:"pph_23"`
	Ppn                    int32     `gorm:"column:ppn" json:"ppn"`
	GrandTotalValueInvA    int32     `gorm:"column:grand_total_value_inv_A" json:"grand_total_value_inv_A"`
	GrandTotalValueInvB    int32     `gorm:"column:grand_total_value_inv_B" json:"grand_total_value_inv_B"`
	Status                 int32     `gorm:"column:status" json:"status"`
	CreatedAt              time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt              time.Time `gorm:"column:updated_at" json:"updated_at"`
	TotalCarRent           string    `gorm:"column:total_car_rent" json:"total_car_rent"`
	OperationalCost        string    `gorm:"column:operational_cost" json:"operational_cost"`
	InvCover               string    `gorm:"column:inv_cover" json:"inv_cover"`
	InvCoverPpn            string    `gorm:"column:inv_cover_ppn" json:"inv_cover_ppn"`
	Summary                string    `gorm:"column:summary" json:"summary"`
	IDUsers                int32     `gorm:"column:id_users" json:"id_users"`
	TypePpn                string    `gorm:"column:type_ppn" json:"type_ppn"`
	DriverInvoice          string    `gorm:"column:driver_invoice" json:"driver_invoice"`
}

// TableName TbCustomInvoiceModel's table name
func (*TbCustomInvoiceModel) TableName() string {
	return TableNameTbCustomInvoiceModel
}
