// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTbCustomInvoiceDriver = "tb_custom_invoice_driver"

// TbCustomInvoiceDriver mapped from table <tb_custom_invoice_driver>
type TbCustomInvoiceDriver struct {
	ID                     int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IDCustomeInvoiceMaster int32     `gorm:"column:id_custome_invoice_master" json:"id_custome_invoice_master"`
	IDDriver               int32     `gorm:"column:id_driver" json:"id_driver"`
	IDIwo                  int32     `gorm:"column:id_iwo" json:"id_iwo"`
	Status                 int32     `gorm:"column:status;default:1" json:"status"`
	CreatedAt              time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt              time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName TbCustomInvoiceDriver's table name
func (*TbCustomInvoiceDriver) TableName() string {
	return TableNameTbCustomInvoiceDriver
}
