// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTbDetailIwo = "tb_detail_iwo"

// TbDetailIwo mapped from table <tb_detail_iwo>
type TbDetailIwo struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IwoID          int32     `gorm:"column:iwo_id" json:"iwo_id"`
	Seragam        string    `gorm:"column:seragam" json:"seragam"`
	Mcu            string    `gorm:"column:mcu" json:"mcu"`
	Training       string    `gorm:"column:training" json:"training"`
	BpjsKesehatanC string    `gorm:"column:bpjs_kesehatan_c" json:"bpjs_kesehatan_c"`
	BpjsTkC        string    `gorm:"column:bpjs_tk_c" json:"bpjs_tk_c"`
	BpjsPensiunC   string    `gorm:"column:bpjs_pensiun_c" json:"bpjs_pensiun_c"`
	UangKompensasi string    `gorm:"column:uang_kompensasi" json:"uang_kompensasi"`
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at" json:"updated_at"`
	Status         int32     `gorm:"column:status;default:1" json:"status"`
	ThrC           string    `gorm:"column:thr_c" json:"thr_c"`
}

// TableName TbDetailIwo's table name
func (*TbDetailIwo) TableName() string {
	return TableNameTbDetailIwo
}
