// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTbDriverAvailable = "tb_driver_available"

// TbDriverAvailable mapped from table <tb_driver_available>
type TbDriverAvailable struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DriverID      int32     `gorm:"column:driver_id;not null" json:"driver_id"`
	Driver        string    `gorm:"column:driver;not null" json:"driver"`
	DriverPhone   string    `gorm:"column:driver_phone;not null" json:"driver_phone"`
	TimeAvailable time.Time `gorm:"column:time_available;not null" json:"time_available"`
	Status        int32     `gorm:"column:status;default:1" json:"status"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TbDriverAvailable's table name
func (*TbDriverAvailable) TableName() string {
	return TableNameTbDriverAvailable
}
