// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTbGsHari = "tb_gs_hari"

// TbGsHari mapped from table <tb_gs_hari>
type TbGsHari struct {
	ID                     int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt              time.Time `gorm:"column:created_at" json:"created_at"`
	IDGs                   int32     `gorm:"column:id_gs" json:"id_gs"`
	IDSalaryArchiveDrivers int32     `gorm:"column:id_salary_archive_drivers" json:"id_salary_archive_drivers"`
	JSONData               string    `gorm:"column:json_data" json:"json_data"`
	JumlahHari             int32     `gorm:"column:jumlah_hari" json:"jumlah_hari"`
	UpdatedAt              time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName TbGsHari's table name
func (*TbGsHari) TableName() string {
	return TableNameTbGsHari
}
