// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTbHistorySlipGaji = "tb_history_slip_gaji"

// TbHistorySlipGaji mapped from table <tb_history_slip_gaji>
type TbHistorySlipGaji struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Bulan     string    `gorm:"column:bulan" json:"bulan"`
	Tahun     string    `gorm:"column:tahun" json:"tahun"`
	Status    int32     `gorm:"column:status" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	TglGaji   string    `gorm:"column:tgl_gaji" json:"tgl_gaji"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName TbHistorySlipGaji's table name
func (*TbHistorySlipGaji) TableName() string {
	return TableNameTbHistorySlipGaji
}
