// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTbInternalCompany = "tb_internal_companies"

// TbInternalCompany mapped from table <tb_internal_companies>
type TbInternalCompany struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CompanyName   string    `gorm:"column:company_name;not null" json:"company_name"`
	Logo          string    `gorm:"column:logo" json:"logo"`
	Address       string    `gorm:"column:address;not null" json:"address"`
	AccountName   string    `gorm:"column:account_name;not null" json:"account_name"`
	AccountNumber string    `gorm:"column:account_number;not null" json:"account_number"`
	AccountBranch string    `gorm:"column:account_branch;not null" json:"account_branch"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName TbInternalCompany's table name
func (*TbInternalCompany) TableName() string {
	return TableNameTbInternalCompany
}
