// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTbKompensasiThr = "tb_kompensasi_thr"

// TbKompensasiThr mapped from table <tb_kompensasi_thr>
type TbKompensasiThr struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IDEmployee int32     `gorm:"column:id_employee" json:"id_employee"`
	Type       string    `gorm:"column:type" json:"type"`
	Nilai      string    `gorm:"column:nilai" json:"nilai"`
	Pph21      string    `gorm:"column:pph21" json:"pph21"`
	Bulan      string    `gorm:"column:bulan" json:"bulan"`
	Tahun      string    `gorm:"column:tahun" json:"tahun"`
	CreatedAt  time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName TbKompensasiThr's table name
func (*TbKompensasiThr) TableName() string {
	return TableNameTbKompensasiThr
}
