// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTbNopoDriver = "tb_nopo_driver"

// TbNopoDriver mapped from table <tb_nopo_driver>
type TbNopoDriver struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IDDriver  int32     `gorm:"column:id_driver" json:"id_driver"`
	Nopol     string    `gorm:"column:nopol" json:"nopol"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName TbNopoDriver's table name
func (*TbNopoDriver) TableName() string {
	return TableNameTbNopoDriver
}
