// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTbOpList = "tb_op_list"

// TbOpList mapped from table <tb_op_list>
type TbOpList struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MasterCompaniesID int32     `gorm:"column:master_companies_id;not null" json:"master_companies_id"`
	CreatedAt         time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TbOpList's table name
func (*TbOpList) TableName() string {
	return TableNameTbOpList
}
