// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTbOutOfTown = "tb_out_of_towns"

// TbOutOfTown mapped from table <tb_out_of_towns>
type TbOutOfTown struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TimesheetID       int32     `gorm:"column:timesheet_id;not null" json:"timesheet_id"`
	City              string    `gorm:"column:city;not null" json:"city"`
	Type              string    `gorm:"column:type;not null;default:Round Trip;comment:Over Night|Round Trip" json:"type"` // Over Night|Round Trip
	CreatedAt         time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at" json:"updated_at"`
	Status            int32     `gorm:"column:status;not null;default:1;comment:1:active | 200:revised" json:"status"` // 1:active | 200:revised
	TimesheetRevision int32     `gorm:"column:timesheet_revision;not null;default:1" json:"timesheet_revision"`
	Lat               string    `gorm:"column:lat" json:"lat"`
	Long              string    `gorm:"column:long" json:"long"`
	FotoAktifitas     string    `gorm:"column:foto_aktifitas" json:"foto_aktifitas"`
}

// TableName TbOutOfTown's table name
func (*TbOutOfTown) TableName() string {
	return TableNameTbOutOfTown
}
