// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTbPic = "tb_pic"

// TbPic mapped from table <tb_pic>
type TbPic struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Email          string    `gorm:"column:email" json:"email"`
	Status         int32     `gorm:"column:status;default:1" json:"status"`
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`
	FullName       string    `gorm:"column:full_name" json:"full_name"`
	HomeAddress    string    `gorm:"column:home_address" json:"home_address"`
	IwoTemplatesID int32     `gorm:"column:iwo_templates_id" json:"iwo_templates_id"`
	PhoneNumber    string    `gorm:"column:phone_number" json:"phone_number"`
	UpdatedAt      time.Time `gorm:"column:updated_at" json:"updated_at"`
	HrGaPosition   string    `gorm:"column:hr_ga_position" json:"hr_ga_position"`
	PicType        string    `gorm:"column:pic_type" json:"pic_type"`
}

// TableName TbPic's table name
func (*TbPic) TableName() string {
	return TableNameTbPic
}
