// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameThrFee = "thr_fees"

// ThrFee mapped from table <thr_fees>
type ThrFee struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`
	ThrFeeType   int32     `gorm:"column:thr_fee_type" json:"thr_fee_type"`
	ThrFeeAmount string    `gorm:"column:thr_fee_amount" json:"thr_fee_amount"`
}

// TableName ThrFee's table name
func (*ThrFee) TableName() string {
	return TableNameThrFee
}
