// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTimesheet = "timesheets"

// Timesheet mapped from table <timesheets>
type Timesheet struct {
	ID                 int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ServiceUsersID     int32     `gorm:"column:service_users_id;not null" json:"service_users_id"`
	ServiceDriversID   int32     `gorm:"column:service_drivers_id" json:"service_drivers_id"`
	Date               string    `gorm:"column:date" json:"date"`
	TimeEntry          string    `gorm:"column:time_entry" json:"time_entry"`
	KmEntry            string    `gorm:"column:km_entry" json:"km_entry"`
	TimeExit           string    `gorm:"column:time_exit" json:"time_exit"`
	KmExit             string    `gorm:"column:km_exit" json:"km_exit"`
	CreatedAt          time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt          time.Time `gorm:"column:updated_at" json:"updated_at"`
	HolidayStatus      int32     `gorm:"column:holiday_status;comment:0:not holiday|1:holiday" json:"holiday_status"` // 0:not holiday|1:holiday
	TimesheetTimestamp int32     `gorm:"column:timesheet_timestamp" json:"timesheet_timestamp"`
	Status             string    `gorm:"column:status" json:"status"`
	Note               string    `gorm:"column:note" json:"note"`
	Version            int32     `gorm:"column:version;default:1" json:"version"`
	FotoKmIn           string    `gorm:"column:foto_km_in" json:"foto_km_in"`
	FotoKmOut          string    `gorm:"column:foto_km_out" json:"foto_km_out"`
	LatMasuk           string    `gorm:"column:lat_masuk" json:"lat_masuk"`
	LongMasuk          string    `gorm:"column:long_masuk" json:"long_masuk"`
	LatKeluar          string    `gorm:"column:lat_keluar" json:"lat_keluar"`
	LongKeluar         string    `gorm:"column:long_keluar" json:"long_keluar"`
	StatusDriver       string    `gorm:"column:status_driver" json:"status_driver"`
	FotoKmInCloud      string    `gorm:"column:foto_km_in_cloud" json:"foto_km_in_cloud"`
	FotoKmOutCloud     string    `gorm:"column:foto_km_out_cloud" json:"foto_km_out_cloud"`
	IDTimesheetsMysql  int32     `gorm:"column:id_timesheets_mysql" json:"id_timesheets_mysql"`
}

// TableName Timesheet's table name
func (*Timesheet) TableName() string {
	return TableNameTimesheet
}
