// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameTokenNotificationApp = "token_notification_apps"

// TokenNotificationApp mapped from table <token_notification_apps>
type TokenNotificationApp struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	EmployeeID string    `gorm:"column:employee_id;not null" json:"employee_id"`
	Token      string    `gorm:"column:token" json:"token"`
	Status     int32     `gorm:"column:status;default:1" json:"status"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TokenNotificationApp's table name
func (*TokenNotificationApp) TableName() string {
	return TableNameTokenNotificationApp
}
