// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql

import (
	"time"
)

const TableNameUsersDriver = "users_driver"

// UsersDriver mapped from table <users_driver>
type UsersDriver struct {
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IDTimesheets      int32     `gorm:"column:id_timesheets" json:"id_timesheets"`
	NamaUsers         string    `gorm:"column:nama_users" json:"nama_users"`
	PlatNomor         string    `gorm:"column:plat_nomor" json:"plat_nomor"`
	NamaPt            string    `gorm:"column:nama_pt" json:"nama_pt"`
	Date              string    `gorm:"column:date" json:"date"`
	CreatedAt         time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at" json:"updated_at"`
	IDTimesheetsMysql int32     `gorm:"column:id_timesheets_mysql" json:"id_timesheets_mysql"`
}

// TableName UsersDriver's table name
func (*UsersDriver) TableName() string {
	return TableNameUsersDriver
}
