// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

const TableNameCutOff = "cut_off"

// CutOff mapped from table <cut_off>
type CutOff struct {
	ID         int32  `gorm:"column:id;primaryKey" json:"id"`
	Periode    string `gorm:"column:periode" json:"periode"`
	StatusData int32  `gorm:"column:status_data" json:"status_data"`
}

// TableName CutOff's table name
func (*CutOff) TableName() string {
	return TableNameCutOff
}
