// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

import (
	"time"
)

const TableNameCutiTImesheet = "Cuti_TImesheets"

// CutiTImesheet mapped from table <Cuti_TImesheets>
type CutiTImesheet struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	EmployeeID        string    `gorm:"column:employee_id" json:"employee_id"`
	Fullname          string    `gorm:"column:fullname" json:"fullname"`
	CompanyName       string    `gorm:"column:company_name" json:"company_name"`
	PhotoTimesheets1  string    `gorm:"column:photo_timesheets1;not null" json:"photo_timesheets1"`
	PhotoTimesheets2  string    `gorm:"column:photo_timesheets2;not null" json:"photo_timesheets2"`
	Bulan             string    `gorm:"column:bulan;not null;default:DefaultValue" json:"bulan"`
	Tahun             int32     `gorm:"column:tahun;not null;default:2024" json:"tahun"`
	StartCutoff       string    `gorm:"column:start_cutoff" json:"start_cutoff"`
	EndCutoff         string    `gorm:"column:end_cutoff" json:"end_cutoff"`
	TanggalGajian     string    `gorm:"column:tanggal_gajian" json:"tanggal_gajian"`
	PeriodeTimesheets string    `gorm:"column:periode_timesheets" json:"periode_timesheets"`
	CreatedAt         time.Time `gorm:"column:created_at" json:"created_at"`
	UpdateAt          time.Time `gorm:"column:update_at" json:"update_at"`
}

// TableName CutiTImesheet's table name
func (*CutiTImesheet) TableName() string {
	return TableNameCutiTImesheet
}
