// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

import (
	"time"
)

const TableNameDriverAvailability = "driver_availability"

// DriverAvailability mapped from table <driver_availability>
type DriverAvailability struct {
	AvailabilityID int32     `gorm:"column:availability_id;primaryKey;autoIncrement:true" json:"availability_id"`
	DriverName     string    `gorm:"column:driver_name;not null" json:"driver_name"`
	Date           time.Time `gorm:"column:date;not null" json:"date"`
	DayName        string    `gorm:"column:day_name;not null" json:"day_name"`
	IsAvailable    bool      `gorm:"column:is_available;not null" json:"is_available"`
	WeekStart      time.Time `gorm:"column:week_start;not null" json:"week_start"`
	WeekEnd        time.Time `gorm:"column:week_end;not null" json:"week_end"`
	CreatedAt      time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DriverID       string    `gorm:"column:driver_id;not null" json:"driver_id"`
	PhoneNumber    string    `gorm:"column:phone_number" json:"phone_number"`
	Domisili       string    `gorm:"column:domisili" json:"domisili"`
}

// TableName DriverAvailability's table name
func (*DriverAvailability) TableName() string {
	return TableNameDriverAvailability
}
