// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

import (
	"time"
)

const TableNameForm2 = "Form_2"

// Form2 mapped from table <Form_2>
type Form2 struct {
	ID                        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Gender                    string    `gorm:"column:gender" json:"gender"`
	Agama                     string    `gorm:"column:agama" json:"agama"`
	StatusPernikahan          string    `gorm:"column:status_pernikahan" json:"status_pernikahan"`
	NoKtp                     string    `gorm:"column:no_ktp" json:"no_ktp"`
	NoNpwp                    string    `gorm:"column:no_npwp" json:"no_npwp"`
	SimANomor                 string    `gorm:"column:sim_a_nomor" json:"sim_a_nomor"`
	SimAMasaBerlaku           time.Time `gorm:"column:sim_a_masa_berlaku;default:CURRENT_TIMESTAMP" json:"sim_a_masa_berlaku"`
	SimB1Nomor                string    `gorm:"column:sim_b1_nomor" json:"sim_b1_nomor"`
	SimB1MasaBerlaku          time.Time `gorm:"column:sim_b1_masa_berlaku;default:CURRENT_TIMESTAMP" json:"sim_b1_masa_berlaku"`
	SimB2Nomor                string    `gorm:"column:sim_b2_nomor" json:"sim_b2_nomor"`
	SimB2MasaBerlaku          time.Time `gorm:"column:sim_b2_masa_berlaku;default:CURRENT_TIMESTAMP" json:"sim_b2_masa_berlaku"`
	AlamatKtp                 string    `gorm:"column:alamat_ktp" json:"alamat_ktp"`
	RtRw                      string    `gorm:"column:rt_rw" json:"rt_rw"`
	Kecamatan                 string    `gorm:"column:kecamatan" json:"kecamatan"`
	Kelurahan                 string    `gorm:"column:kelurahan" json:"kelurahan"`
	KodePos                   string    `gorm:"column:kode_pos" json:"kode_pos"`
	AlamatTempatTinggal       string    `gorm:"column:alamat_tempat_tinggal" json:"alamat_tempat_tinggal"`
	RtRwTempatTinggal         string    `gorm:"column:rt_rw_tempat_tinggal" json:"rt_rw_tempat_tinggal"`
	KecamatanTempatTinggal    string    `gorm:"column:kecamatan_tempat_tinggal" json:"kecamatan_tempat_tinggal"`
	KelurahanTempatTinggal    string    `gorm:"column:kelurahan_tempat_tinggal" json:"kelurahan_tempat_tinggal"`
	KodePosTempatTinggal      string    `gorm:"column:kode_pos_tempat_tinggal" json:"kode_pos_tempat_tinggal"`
	NamaKepalaRt              string    `gorm:"column:nama_kepala_rt" json:"nama_kepala_rt"`
	NeTelpRt                  string    `gorm:"column:ne_telp_rt" json:"ne_telp_rt"`
	NamaKontakDarurat         string    `gorm:"column:nama_kontak_darurat" json:"nama_kontak_darurat"`
	TelponeKontakDarurat      string    `gorm:"column:telpone_kontak_darurat" json:"telpone_kontak_darurat"`
	HubunganKontakDarurat     string    `gorm:"column:hubungan_kontak_darurat" json:"hubungan_kontak_darurat"`
	PendidikanTerakhir        string    `gorm:"column:pendidikan_terakhir" json:"pendidikan_terakhir"`
	DefensiveDriving          string    `gorm:"column:defensive_driving" json:"defensive_driving"`
	PendidikanInformal        string    `gorm:"column:pendidikan_informal" json:"pendidikan_informal"`
	BahasaInggris             string    `gorm:"column:bahasa_inggris" json:"bahasa_inggris"`
	BahasaJepang              string    `gorm:"column:bahasa_jepang" json:"bahasa_jepang"`
	PengalamanTahunMulai      int32     `gorm:"column:pengalaman_tahun_mulai" json:"pengalaman_tahun_mulai"`
	PengalamanTahunSelesai    int32     `gorm:"column:pengalaman_tahun_selesai" json:"pengalaman_tahun_selesai"`
	PengalamanNamaPerusahaan  string    `gorm:"column:pengalaman_nama_perusahaan" json:"pengalaman_nama_perusahaan"`
	PengalamanUserEkspat      string    `gorm:"column:pengalaman_user_ekspat" json:"pengalaman_user_ekspat"`
	PengalamanNegaraAsal      string    `gorm:"column:pengalaman_negara_asal" json:"pengalaman_negara_asal"`
	PengalamanTahunMulai2     int32     `gorm:"column:pengalaman_tahun_mulai2" json:"pengalaman_tahun_mulai2"`
	PengalamanTahunSelesai2   int32     `gorm:"column:pengalaman_tahun_selesai2" json:"pengalaman_tahun_selesai2"`
	PengalamanNamaPerusahaan2 string    `gorm:"column:pengalaman_nama_perusahaan2" json:"pengalaman_nama_perusahaan2"`
	PengalamanUserEkspat2     string    `gorm:"column:pengalaman_user_ekspat2" json:"pengalaman_user_ekspat2"`
	PengalamanNegaraAsal2     string    `gorm:"column:pengalaman_negara_asal2" json:"pengalaman_negara_asal2"`
	PengalamanTahunMulai3     int32     `gorm:"column:pengalaman_tahun_mulai3" json:"pengalaman_tahun_mulai3"`
	PengalamanTahunSelesai3   int32     `gorm:"column:pengalaman_tahun_selesai3" json:"pengalaman_tahun_selesai3"`
	PengalamanNamaPerusahaan3 string    `gorm:"column:pengalaman_nama_perusahaan3" json:"pengalaman_nama_perusahaan3"`
	PengalamanUserEkspat3     string    `gorm:"column:pengalaman_user_ekspat3" json:"pengalaman_user_ekspat3"`
	PengalamanNegaraAsal3     string    `gorm:"column:pengalaman_negara_asal3" json:"pengalaman_negara_asal3"`
	BersediaMenaatiPeraturan  string    `gorm:"column:bersedia_menaati_peraturan" json:"bersedia_menaati_peraturan"`
	BersediaBekerjaLembur     string    `gorm:"column:bersedia_bekerja_lembur" json:"bersedia_bekerja_lembur"`
	BersediaBekerjaShiftMalam string    `gorm:"column:bersedia_bekerja_shift_malam" json:"bersedia_bekerja_shift_malam"`
	BersediaHariLibur         string    `gorm:"column:bersedia_hari_libur" json:"bersedia_hari_libur"`
	BersediaTempatkanLain     string    `gorm:"column:bersedia_tempatkan_lain" json:"bersedia_tempatkan_lain"`
	BersediaRahasia           string    `gorm:"column:bersedia_rahasia" json:"bersedia_rahasia"`
	BersediaProses            string    `gorm:"column:bersedia_proses" json:"bersedia_proses"`
	BersediaSuratPernyataan   string    `gorm:"column:bersedia_surat_pernyataan" json:"bersedia_surat_pernyataan"`
	BersediaDriverUser        string    `gorm:"column:bersedia_driver_user" json:"bersedia_driver_user"`
	BersediaDriverFamily      string    `gorm:"column:bersedia_driver_family" json:"bersedia_driver_family"`
	Form1ID                   int32     `gorm:"column:form_1_id" json:"form_1_id"`
	CreatedAt                 time.Time `gorm:"column:createdAt;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt                 time.Time `gorm:"column:updatedAt" json:"updatedAt"`
	NamaLengkap               string    `gorm:"column:nama_lengkap" json:"nama_lengkap"`
	NoTelphone                string    `gorm:"column:no_telphone" json:"no_telphone"`
	NomorBerkas               string    `gorm:"column:nomor_berkas" json:"nomor_berkas"`
	Bank                      string    `gorm:"column:bank" json:"bank"`
	Norek                     string    `gorm:"column:norek" json:"norek"`
	TanggalLahir              string    `gorm:"column:tanggal_lahir" json:"tanggal_lahir"`
}

// TableName Form2's table name
func (*Form2) TableName() string {
	return TableNameForm2
}
