// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

import (
	"time"
)

const TableNameForm5 = "Form_5"

// Form5 mapped from table <Form_5>
type Form5 struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BeradaDiKantor string    `gorm:"column:berada_di_kantor;not null" json:"berada_di_kantor"`
	Timestamp      time.Time `gorm:"column:timestamp;not null;default:CURRENT_TIMESTAMP" json:"timestamp"`
	Tanggal        time.Time `gorm:"column:tanggal" json:"tanggal"`
	Jam            string    `gorm:"column:jam" json:"jam"`
	Status         string    `gorm:"column:status" json:"status"`
	Channel        string    `gorm:"column:channel" json:"channel"`
	Form1ID        int32     `gorm:"column:form_1_id;not null" json:"form_1_id"`
	CreatedAt      time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt      time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
	NamaLengkap    string    `gorm:"column:nama_lengkap" json:"nama_lengkap"`
	NoTelphone     string    `gorm:"column:no_telphone" json:"no_telphone"`
	NomorBerkas    string    `gorm:"column:nomor_berkas" json:"nomor_berkas"`
}

// TableName Form5's table name
func (*Form5) TableName() string {
	return TableNameForm5
}
