// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

import (
	"time"
)

const TableNameForm3 = "Form_3"

// Form3 mapped from table <Form_3>
type Form3 struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Tes1        string    `gorm:"column:tes_1" json:"tes_1"`
	Tes1Score   int32     `gorm:"column:tes_1_score" json:"tes_1_score"`
	Tes2        string    `gorm:"column:tes_2" json:"tes_2"`
	Tes2Score   int32     `gorm:"column:tes_2_score" json:"tes_2_score"`
	Tes3        string    `gorm:"column:tes_3" json:"tes_3"`
	Tes3Score   int32     `gorm:"column:tes_3_score" json:"tes_3_score"`
	Tes4        string    `gorm:"column:tes_4" json:"tes_4"`
	Tes4Score   int32     `gorm:"column:tes_4_score" json:"tes_4_score"`
	Tes5        string    `gorm:"column:tes_5" json:"tes_5"`
	Tes5Score   int32     `gorm:"column:tes_5_score" json:"tes_5_score"`
	Tes6        string    `gorm:"column:tes_6" json:"tes_6"`
	Tes6Score   int32     `gorm:"column:tes_6_score" json:"tes_6_score"`
	Tes7        string    `gorm:"column:tes_7" json:"tes_7"`
	Tes7Score   int32     `gorm:"column:tes_7_score" json:"tes_7_score"`
	Tes8        string    `gorm:"column:tes_8" json:"tes_8"`
	Tes8Score   int32     `gorm:"column:tes_8_score" json:"tes_8_score"`
	Tes9        string    `gorm:"column:tes_9" json:"tes_9"`
	Tes9Score   int32     `gorm:"column:tes_9_score" json:"tes_9_score"`
	Tes10       string    `gorm:"column:tes_10" json:"tes_10"`
	Tes10Score  int32     `gorm:"column:tes_10_score" json:"tes_10_score"`
	Tes11       string    `gorm:"column:tes_11" json:"tes_11"`
	Tes11Score  int32     `gorm:"column:tes_11_score" json:"tes_11_score"`
	Tes12       string    `gorm:"column:tes_12" json:"tes_12"`
	Tes12Score  int32     `gorm:"column:tes_12_score" json:"tes_12_score"`
	Tes13       string    `gorm:"column:tes_13" json:"tes_13"`
	Tes13Score  int32     `gorm:"column:tes_13_score" json:"tes_13_score"`
	Tes14       string    `gorm:"column:tes_14" json:"tes_14"`
	Tes14Score  int32     `gorm:"column:tes_14_score" json:"tes_14_score"`
	Tes15       string    `gorm:"column:tes_15" json:"tes_15"`
	Tes15Score  int32     `gorm:"column:tes_15_score" json:"tes_15_score"`
	Tes16       string    `gorm:"column:tes_16" json:"tes_16"`
	Tes16Score  int32     `gorm:"column:tes_16_score" json:"tes_16_score"`
	Tes17       string    `gorm:"column:tes_17" json:"tes_17"`
	Tes17Score  int32     `gorm:"column:tes_17_score" json:"tes_17_score"`
	Tes18       string    `gorm:"column:tes_18" json:"tes_18"`
	Tes18Score  int32     `gorm:"column:tes_18_score" json:"tes_18_score"`
	Tes19       string    `gorm:"column:tes_19" json:"tes_19"`
	Tes19Score  int32     `gorm:"column:tes_19_score" json:"tes_19_score"`
	Tes20       string    `gorm:"column:tes_20" json:"tes_20"`
	Tes20Score  int32     `gorm:"column:tes_20_score" json:"tes_20_score"`
	Tes21       string    `gorm:"column:tes_21" json:"tes_21"`
	Tes21Score  int32     `gorm:"column:tes_21_score" json:"tes_21_score"`
	Status      string    `gorm:"column:status" json:"status"`
	Form1ID     int32     `gorm:"column:form_1_id" json:"form_1_id"`
	CreatedAt   time.Time `gorm:"column:createdAt;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt   time.Time `gorm:"column:updatedAt" json:"updatedAt"`
	NamaLengkap string    `gorm:"column:nama_lengkap" json:"nama_lengkap"`
	NoTelphone  string    `gorm:"column:no_telphone" json:"no_telphone"`
	NomorBerkas string    `gorm:"column:nomor_berkas" json:"nomor_berkas"`
}

// TableName Form3's table name
func (*Form3) TableName() string {
	return TableNameForm3
}
