// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

import (
	"time"
)

const TableNameForm1 = "Form_1"

// Form1 mapped from table <Form_1>
type Form1 struct {
	ID                        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NamaLengkap               string    `gorm:"column:nama_lengkap" json:"nama_lengkap"`
	NomorBerkas               string    `gorm:"column:nomor_berkas;not null" json:"nomor_berkas"`
	NamaPanggilan             string    `gorm:"column:nama_panggilan" json:"nama_panggilan"`
	NoTelphone                string    `gorm:"column:no_telphone" json:"no_telphone"`
	TahunLahir                string    `gorm:"column:tahun_lahir" json:"tahun_lahir"`
	NamaKotaDomisili          string    `gorm:"column:nama_kota_domisili" json:"nama_kota_domisili"`
	OrangYangMerekomendasikan string    `gorm:"column:orang_yang_merekomendasikan" json:"orang_yang_merekomendasikan"`
	NamaRekomendasi           string    `gorm:"column:nama_rekomendasi" json:"nama_rekomendasi"`
	NoTelphoneRekomendasi     string    `gorm:"column:no_telphone_rekomendasi" json:"no_telphone_rekomendasi"`
	NamaPtRekomendasi         string    `gorm:"column:nama_pt_rekomendasi" json:"nama_pt_rekomendasi"`
	URLForm                   string    `gorm:"column:url_form" json:"url_form"`
	PengalamanJepang          bool      `gorm:"column:pengalaman_jepang" json:"pengalaman_jepang"`
	CreatedAt                 time.Time `gorm:"column:createdAt;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt                 time.Time `gorm:"column:updatedAt" json:"updatedAt"`
	TempatLahir               string    `gorm:"column:tempat_lahir" json:"tempat_lahir"`
}

// TableName Form1's table name
func (*Form1) TableName() string {
	return TableNameForm1
}
