// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

import (
	"time"
)

const TableNameForm4 = "Form_4"

// Form4 mapped from table <Form_4>
type Form4 struct {
	ID                         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FotoDiri                   string    `gorm:"column:foto_diri" json:"foto_diri"`
	Sim                        string    `gorm:"column:sim" json:"sim"`
	Ktp                        string    `gorm:"column:ktp" json:"ktp"`
	KartuKeluarga              string    `gorm:"column:kartu_keluarga" json:"kartu_keluarga"`
	Cv                         string    `gorm:"column:cv" json:"cv"`
	KetNarkoba                 string    `gorm:"column:ket_narkoba" json:"ket_narkoba"`
	Sksck                      string    `gorm:"column:sksck" json:"sksck"`
	Domisili                   string    `gorm:"column:domisili" json:"domisili"`
	KeteranganKerja            string    `gorm:"column:keterangan_kerja" json:"keterangan_kerja"`
	Sehat                      string    `gorm:"column:sehat" json:"sehat"`
	Pernyataan                 string    `gorm:"column:pernyataan" json:"pernyataan"`
	Form1ID                    int32     `gorm:"column:form_1_id" json:"form_1_id"`
	CreatedAt                  time.Time `gorm:"column:createdAt;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt                  time.Time `gorm:"column:updatedAt" json:"updatedAt"`
	NamaLengkap                string    `gorm:"column:nama_lengkap" json:"nama_lengkap"`
	NoTelphone                 string    `gorm:"column:no_telphone" json:"no_telphone"`
	NomorBerkas                string    `gorm:"column:nomor_berkas" json:"nomor_berkas"`
	SertifikatDefensiveDriving string    `gorm:"column:sertifikat_defensive_driving" json:"sertifikat_defensive_driving"`
}

// TableName Form4's table name
func (*Form4) TableName() string {
	return TableNameForm4
}
