// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

const TableNameJobHolder = "job_holder"

// JobHolder mapped from table <job_holder>
type JobHolder struct {
	ID                   int32  `gorm:"column:id;primaryKey" json:"id"`
	NoID                 int32  `gorm:"column:no_id" json:"no_id"`
	NoAgrement           string `gorm:"column:no_agrement" json:"no_agrement"`
	DriverName           string `gorm:"column:driver_name" json:"driver_name"`
	IDCard               string `gorm:"column:id_card" json:"id_card"`
	CutOff               string `gorm:"column:cut_off" json:"cut_off"`
	Seragam              string `gorm:"column:seragam" json:"seragam"`
	JumlahKaryawan       string `gorm:"column:jumlah_karyawan" json:"jumlah_karyawan"`
	JobRole              string `gorm:"column:job_role" json:"job_role"`
	Username             string `gorm:"column:username" json:"username"`
	Area                 string `gorm:"column:area" json:"area"`
	NoTelphone           string `gorm:"column:no_telphone" json:"no_telphone"`
	NomorHpIstriKeluarga string `gorm:"column:nomor_hp_istri_keluarga" json:"nomor_hp_istri_keluarga"`
	DateJoin             string `gorm:"column:date_join" json:"date_join"`
	NoSim                string `gorm:"column:no_sim" json:"no_sim"`
	MasaBerlakuSim       string `gorm:"column:masa_berlaku_sim" json:"masa_berlaku_sim"`
	RemainingSim         string `gorm:"column:remaining_sim" json:"remaining_sim"`
	GradeSim             string `gorm:"column:grade_sim" json:"grade_sim"`
	PembayaranGaji       string `gorm:"column:pembayaran_gaji" json:"pembayaran_gaji"`
	Status               string `gorm:"column:status" json:"status"`
	NoBerkas             string `gorm:"column:no_berkas" json:"no_berkas"`
	NoKtp                string `gorm:"column:no_ktp" json:"no_ktp"`
	NoNpwp               string `gorm:"column:no_npwp" json:"no_npwp"`
	StatusPernikahan     string `gorm:"column:status_pernikahan" json:"status_pernikahan"`
	JenisBank            string `gorm:"column:jenis_bank" json:"jenis_bank"`
	NoRekening           string `gorm:"column:no_rekening" json:"no_rekening"`
	UmurSaatJoin         string `gorm:"column:umur_saat_join" json:"umur_saat_join"`
	BrithDate            string `gorm:"column:brith_date" json:"brith_date"`
	Age                  string `gorm:"column:age" json:"age"`
	Religion             string `gorm:"column:religion" json:"religion"`
	StartAgreement       string `gorm:"column:start_agreement" json:"start_agreement"`
	EndAgreement         string `gorm:"column:end_agreement" json:"end_agreement"`
	Bulan                string `gorm:"column:bulan" json:"bulan"`
	Tahun                string `gorm:"column:tahun" json:"tahun"`
	Uuck                 string `gorm:"column:uuck" json:"uuck"`
	Training             string `gorm:"column:training" json:"training"`
	Mcu                  string `gorm:"column:mcu" json:"mcu"`
	BajuSeragam          string `gorm:"column:baju_seragam" json:"baju_seragam"`
	Thr                  string `gorm:"column:thr" json:"thr"`
	Basic                string `gorm:"column:basic" json:"basic"`
	BpjsTk               string `gorm:"column:bpjs_tk" json:"bpjs_tk"`
	CustomerID           int32  `gorm:"column:customer_id" json:"customer_id"`
	EmployeeID           string `gorm:"column:employee_id" json:"employee_id"`
}

// TableName JobHolder's table name
func (*JobHolder) TableName() string {
	return TableNameJobHolder
}
