// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

const TableNameTbBlastingDriver = "tb_blasting_driver"

// TbBlastingDriver mapped from table <tb_blasting_driver>
type TbBlastingDriver struct {
	NamaDriver string `gorm:"column:nama_driver" json:"nama_driver"`
	NamaBank   string `gorm:"column:nama_bank" json:"nama_bank"`
	NoRekening string `gorm:"column:no_rekening" json:"no_rekening"`
	NoTelepon  string `gorm:"column:no_telepon" json:"no_telepon"`
	ID         int64  `gorm:"column:id;primaryKey" json:"id"`
}

// TableName TbBlastingDriver's table name
func (*TbBlastingDriver) TableName() string {
	return TableNameTbBlastingDriver
}
