// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

import (
	"time"
)

const TableNameTbHistoryBlastUser = "tb_history_blast_user"

// TbHistoryBlastUser mapped from table <tb_history_blast_user>
type TbHistoryBlastUser struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Userphonenumber string    `gorm:"column:userphonenumber" json:"userphonenumber"`
	Pesan           string    `gorm:"column:pesan" json:"pesan"`
	CreatedAt       time.Time `gorm:"column:created_at" json:"created_at"`
	UpdateAt        time.Time `gorm:"column:update_at" json:"update_at"`
	Status          int32     `gorm:"column:status" json:"status"`
	Datedetails     string    `gorm:"column:datedetails" json:"datedetails"`
}

// TableName TbHistoryBlastUser's table name
func (*TbHistoryBlastUser) TableName() string {
	return TableNameTbHistoryBlastUser
}
