// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

import (
	"time"
)

const TableNameTbIwoURL = "tb_iwo_url"

// TbIwoURL mapped from table <tb_iwo_url>
type TbIwoURL struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Tanggal        string    `gorm:"column:tanggal" json:"tanggal"`
	URLPdf         string    `gorm:"column:url_pdf" json:"url_pdf"`
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`
	UpdateAt       time.Time `gorm:"column:update_at" json:"update_at"`
	IDIwoTemplates string    `gorm:"column:id_iwo_templates" json:"id_iwo_templates"`
}

// TableName TbIwoURL's table name
func (*TbIwoURL) TableName() string {
	return TableNameTbIwoURL
}
