// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

import (
	"time"
)

const TableNameTbJobHolder = "tb_job_holder"

// TbJobHolder mapped from table <tb_job_holder>
type TbJobHolder struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	EmployeeID       string    `gorm:"column:employee_id" json:"employee_id"`
	TglJobHolder     string    `gorm:"column:tgl_job_holder" json:"tgl_job_holder"`
	IDCustomer       int32     `gorm:"column:id_customer" json:"id_customer"`
	IDStatusDataDiri int32     `gorm:"column:id_status_data_diri" json:"id_status_data_diri"`
	CreatedAt        time.Time `gorm:"column:created_at" json:"created_at"`
	IDUsers          int32     `gorm:"column:id_users" json:"id_users"`
}

// TableName TbJobHolder's table name
func (*TbJobHolder) TableName() string {
	return TableNameTbJobHolder
}
