// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

import (
	"time"
)

const TableNameTbMasterDataDiri = "tb_master_data_diri"

// TbMasterDataDiri mapped from table <tb_master_data_diri>
type TbMasterDataDiri struct {
	ID                    int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NoBerkas              string    `gorm:"column:no_berkas" json:"no_berkas"`
	IDKaryawan            string    `gorm:"column:id_karyawan" json:"id_karyawan"`
	Nama                  string    `gorm:"column:nama" json:"nama"`
	TempatLahir           string    `gorm:"column:tempat_lahir" json:"tempat_lahir"`
	TglLahir              string    `gorm:"column:tgl_lahir" json:"tgl_lahir"`
	Agama                 string    `gorm:"column:agama" json:"agama"`
	NoTelp                string    `gorm:"column:no_telp" json:"no_telp"`
	Bank                  string    `gorm:"column:bank" json:"bank"`
	Norek                 string    `gorm:"column:norek" json:"norek"`
	StatusKawin           string    `gorm:"column:status_kawin" json:"status_kawin"`
	NamaKontakDarurat     string    `gorm:"column:nama_kontak_darurat" json:"nama_kontak_darurat"`
	NoKontakDarurat       string    `gorm:"column:no_kontak_darurat" json:"no_kontak_darurat"`
	HubunganKontakDarurat string    `gorm:"column:hubungan_kontak_darurat" json:"hubungan_kontak_darurat"`
	StatusKaryawan        string    `gorm:"column:status_karyawan" json:"status_karyawan"`
	Domisili              string    `gorm:"column:domisili" json:"domisili"`
	HomeAddres            string    `gorm:"column:home_addres" json:"home_addres"`
	Usia                  string    `gorm:"column:usia" json:"usia"`
	Foto                  string    `gorm:"column:foto" json:"foto"`
	Logo                  string    `gorm:"column:logo" json:"logo"`
	Form1ID               int32     `gorm:"column:form_1_id" json:"form_1_id"`
	CreatedAt             time.Time `gorm:"column:created_at" json:"created_at"`
	EmployeeID            string    `gorm:"column:employee_id" json:"employee_id"`
}

// TableName TbMasterDataDiri's table name
func (*TbMasterDataDiri) TableName() string {
	return TableNameTbMasterDataDiri
}
