// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

import (
	"time"
)

const TableNameTbSim = "tb_sim"

// TbSim mapped from table <tb_sim>
type TbSim struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TypeSim          string    `gorm:"column:type_sim" json:"type_sim"`
	NoSim            string    `gorm:"column:no_sim" json:"no_sim"`
	MasaBerlakuSim   string    `gorm:"column:masa_berlaku_sim" json:"masa_berlaku_sim"`
	CreatedAt        time.Time `gorm:"column:created_at" json:"created_at"`
	IDMasterDataDiri int32     `gorm:"column:id_master_data_diri" json:"id_master_data_diri"`
	FileSim          string    `gorm:"column:file_sim" json:"file_sim"`
}

// TableName TbSim's table name
func (*TbSim) TableName() string {
	return TableNameTbSim
}
