// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

import (
	"time"
)

const TableNameTbStatusDiri = "tb_status_diri"

// TbStatusDiri mapped from table <tb_status_diri>
type TbStatusDiri struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Tanggal          string    `gorm:"column:tanggal" json:"tanggal"`
	Status           string    `gorm:"column:status" json:"status"`
	Alasan           string    `gorm:"column:alasan" json:"alasan"`
	IDMasterDataDiri int32     `gorm:"column:id_master_data_diri;not null" json:"id_master_data_diri"`
	IDPerusahaan     int32     `gorm:"column:id_perusahaan" json:"id_perusahaan"`
	CreatedAt        time.Time `gorm:"column:created_at" json:"created_at"`
	StatusTurun      string    `gorm:"column:status_turun" json:"status_turun"`
}

// TableName TbStatusDiri's table name
func (*TbStatusDiri) TableName() string {
	return TableNameTbStatusDiri
}
