// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package modals

import (
	"time"
)

const TableNameTimesheetDriver = "timesheet_driver"

// TimesheetDriver mapped from table <timesheet_driver>
type TimesheetDriver struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	EmployeeID     string    `gorm:"column:employee_id" json:"employee_id"`
	Perusahaan     string    `gorm:"column:perusahaan" json:"perusahaan"`
	CustomerID     string    `gorm:"column:customer_id" json:"customer_id"`
	Customer       string    `gorm:"column:customer" json:"customer"`
	DriverName     string    `gorm:"column:Driver_Name" json:"Driver_Name"`
	CutOff         string    `gorm:"column:cut_off" json:"cut_off"`
	NoTelp         string    `gorm:"column:no_telp" json:"no_telp"`
	PembayaranGaji string    `gorm:"column:pembayaran_gaji" json:"pembayaran_gaji"`
	Keterangan     string    `gorm:"column:keterangan" json:"keterangan"`
	IDCutOff       int32     `gorm:"column:id_cut_off" json:"id_cut_off"`
	IDCompany      int32     `gorm:"column:id_company" json:"id_company"`
	StatusData     int32     `gorm:"column:status_data" json:"status_data"`
	Bulan          string    `gorm:"column:bulan" json:"bulan"`
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName TimesheetDriver's table name
func (*TimesheetDriver) TableName() string {
	return TableNameTimesheetDriver
}
