// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package postgres

import (
	"time"
)

const TableNameForm6 = "Form_6"

// Form6 mapped from table <Form_6>
type Form6 struct {
	ID                                    int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CheckNamaLengkap                      string    `gorm:"column:check_nama_lengkap;not null" json:"check_nama_lengkap"`
	CheckNomorBerkas                      string    `gorm:"column:check_nomor_berkas;not null" json:"check_nomor_berkas"`
	CheckNamaPanggilan                    string    `gorm:"column:check_nama_panggilan;not null" json:"check_nama_panggilan"`
	CheckTahunLahir                       string    `gorm:"column:check_tahun_lahir;not null" json:"check_tahun_lahir"`
	CheckNamaKotaDomisili                 string    `gorm:"column:check_nama_kota_domisili;not null" json:"check_nama_kota_domisili"`
	CheckOrangYangMerekomendasikan        string    `gorm:"column:check_orang_yang_merekomendasikan;not null" json:"check_orang_yang_merekomendasikan"`
	CheckPengalamanJepang                 string    `gorm:"column:check_pengalamanJepang;not null" json:"check_pengalamanJepang"`
	CheckDataPribadi                      string    `gorm:"column:check_data_pribadi;not null" json:"check_data_pribadi"`
	CheckSim                              string    `gorm:"column:check_sim;not null" json:"check_sim"`
	CheckTempatTinggalDanInformasiDarurat string    `gorm:"column:check_tempat_tinggal_dan_informasi_darurat;not null" json:"check_tempat_tinggal_dan_informasi_darurat"`
	CheckKemampuanDanPendidikan           string    `gorm:"column:check_kemampuan_dan_pendidikan;not null" json:"check_kemampuan_dan_pendidikan"`
	CheckPengalamanKerja1                 string    `gorm:"column:check_pengalaman_kerja1;not null" json:"check_pengalaman_kerja1"`
	CheckPengalamanKerja2                 string    `gorm:"column:check_pengalaman_kerja2;not null" json:"check_pengalaman_kerja2"`
	CheckPengalamanKerja3                 string    `gorm:"column:check_pengalaman_kerja3;not null" json:"check_pengalaman_kerja3"`
	CheckPernyataanKesediaan              string    `gorm:"column:check_pernyataan_kesediaan;not null" json:"check_pernyataan_kesediaan"`
	CheckFotoDiri                         string    `gorm:"column:check_foto_diri;not null" json:"check_foto_diri"`
	CheckFotoSim                          string    `gorm:"column:check_foto_sim;not null" json:"check_foto_sim"`
	CheckFotoKtp                          string    `gorm:"column:check_foto_ktp;not null" json:"check_foto_ktp"`
	CheckFotoKartuKeluarga                string    `gorm:"column:check_foto_kartu_keluarga;not null" json:"check_foto_kartu_keluarga"`
	CheckFotoCv                           string    `gorm:"column:check_foto_cv;not null" json:"check_foto_cv"`
	CheckFotoKetNarkoba                   string    `gorm:"column:check_foto_ket_narkoba;not null" json:"check_foto_ket_narkoba"`
	CheckFotoSkck                         string    `gorm:"column:check_foto_skck;not null" json:"check_foto_skck"`
	CheckFotoKeteranganDomisili           string    `gorm:"column:check_foto_keterangan_domisili;not null" json:"check_foto_keterangan_domisili"`
	CheckFotoKeteranganSehat              string    `gorm:"column:check_foto_keterangan_sehat;not null" json:"check_foto_keterangan_sehat"`
	CheckFotoPernyataanTidakButaWarna     string    `gorm:"column:check_foto_pernyataan_tidak_buta_warna;not null" json:"check_foto_pernyataan_tidak_buta_warna"`
	CheckFotoKeteranganKerja              string    `gorm:"column:check_foto_keterangan_kerja;not null" json:"check_foto_keterangan_kerja"`
	Pertanyaan1                           string    `gorm:"column:pertanyaan_1;not null" json:"pertanyaan_1"`
	Pertanyaan2                           string    `gorm:"column:pertanyaan_2;not null" json:"pertanyaan_2"`
	Pertanyaan3                           string    `gorm:"column:pertanyaan_3;not null" json:"pertanyaan_3"`
	Pertanyaan4                           string    `gorm:"column:pertanyaan_4;not null" json:"pertanyaan_4"`
	Pertanyaan5                           string    `gorm:"column:pertanyaan_5;not null" json:"pertanyaan_5"`
	Pertanyaan6                           string    `gorm:"column:pertanyaan_6;not null" json:"pertanyaan_6"`
	Kerapihan                             string    `gorm:"column:kerapihan;not null" json:"kerapihan"`
	KemampuanBahasaInggris                string    `gorm:"column:kemampuanBahasaInggris;not null" json:"kemampuanBahasaInggris"`
	KemampuanStudiKasus                   string    `gorm:"column:kemampuanStudiKasus;not null" json:"kemampuanStudiKasus"`
	Form1ID                               int32     `gorm:"column:form_1_id;not null" json:"form_1_id"`
	CreatedAt                             time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt                             time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
	NoTelphone                            string    `gorm:"column:no_telphone;not null" json:"no_telphone"`
	NamaLengkap                           string    `gorm:"column:nama_lengkap;not null" json:"nama_lengkap"`
	NomorBerkas                           string    `gorm:"column:nomor_berkas;not null" json:"nomor_berkas"`
	Form2ID                               int32     `gorm:"column:form_2_id" json:"form_2_id"`
	Form4ID                               int32     `gorm:"column:form_4_id" json:"form_4_id"`
	FotoCv                                string    `gorm:"column:foto_cv" json:"foto_cv"`
	CheckSertifikatDefensiveDriving       string    `gorm:"column:check_sertifikat_defensive_driving" json:"check_sertifikat_defensive_driving"`
}

// TableName Form6's table name
func (*Form6) TableName() string {
	return TableNameForm6
}
