// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package postgres

const TableNameMobil = "mobils"

// Mobil mapped from table <mobils>
type Mobil struct {
	ID    int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Nama  string `gorm:"column:nama" json:"nama"`
	Harga int64  `gorm:"column:harga" json:"harga"`
}

// TableName Mobil's table name
func (*Mobil) TableName() string {
	return TableNameMobil
}
