// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package postgres

const TableNameN8nChatHistory = "n8n_chat_histories"

// N8nChatHistory mapped from table <n8n_chat_histories>
type N8nChatHistory struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SessionID string `gorm:"column:session_id;not null" json:"session_id"`
	Message   string `gorm:"column:message;not null" json:"message"`
}

// TableName N8nChatHistory's table name
func (*N8nChatHistory) TableName() string {
	return TableNameN8nChatHistory
}
