// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package postgres

const TableNameProduct = "products"

// Product mapped from table <products>
type Product struct {
	ID    int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name  string `gorm:"column:name" json:"name"`
	Price int64  `gorm:"column:price" json:"price"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
