// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package postgres

import (
	"time"
)

const TableNameTbHistoryBlastDriver = "tb_history_blast_driver"

// TbHistoryBlastDriver mapped from table <tb_history_blast_driver>
type TbHistoryBlastDriver struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Gsphonenumber string    `gorm:"column:gsphonenumber" json:"gsphonenumber"`
	Datedetails   string    `gorm:"column:datedetails" json:"datedetails"`
	Pesan         string    `gorm:"column:pesan" json:"pesan"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdateAt      time.Time `gorm:"column:update_at" json:"update_at"`
	Status        int32     `gorm:"column:status" json:"status"`
}

// TableName TbHistoryBlastDriver's table name
func (*TbHistoryBlastDriver) TableName() string {
	return TableNameTbHistoryBlastDriver
}
