// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package postgres

import (
	"time"
)

const TableNameTbLogDataDiri = "tb_log_data_diri"

// TbLogDataDiri mapped from table <tb_log_data_diri>
type TbLogDataDiri struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TglLog           string    `gorm:"column:tgl_log" json:"tgl_log"`
	IDUsers          int32     `gorm:"column:id_users" json:"id_users"`
	IDMasterDataDiri int32     `gorm:"column:id_master_data_diri" json:"id_master_data_diri"`
	CreatedAt        time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName TbLogDataDiri's table name
func (*TbLogDataDiri) TableName() string {
	return TableNameTbLogDataDiri
}
