// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package postgres

import (
	"time"
)

const TableNameTbPengalaman = "tb_pengalaman"

// TbPengalaman mapped from table <tb_pengalaman>
type TbPengalaman struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TahunAwal        string    `gorm:"column:tahun_awal" json:"tahun_awal"`
	TahunAkhir       string    `gorm:"column:tahun_akhir" json:"tahun_akhir"`
	Perusahaan       string    `gorm:"column:perusahaan" json:"perusahaan"`
	Jabatan          string    `gorm:"column:jabatan" json:"jabatan"`
	CreatedAt        time.Time `gorm:"column:created_at" json:"created_at"`
	IDMasterDataDiri int32     `gorm:"column:id_master_data_diri" json:"id_master_data_diri"`
}

// TableName TbPengalaman's table name
func (*TbPengalaman) TableName() string {
	return TableNameTbPengalaman
}
