// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package postgres

const TableNameTbPendukungTbMasterDataDiri = "tb_pendukung_tb_master_data_diri"

// TbPendukungTbMasterDataDiri mapped from table <tb_pendukung_tb_master_data_diri>
type TbPendukungTbMasterDataDiri struct {
	ID               int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Ktp              string `gorm:"column:ktp" json:"ktp"`
	Npwp             string `gorm:"column:npwp" json:"npwp"`
	BahaInggris      string `gorm:"column:baha_inggris" json:"baha_inggris"`
	Gender           string `gorm:"column:gender" json:"gender"`
	IDMasterDataDiri int32  `gorm:"column:id_master_data_diri" json:"id_master_data_diri"`
}

// TableName TbPendukungTbMasterDataDiri's table name
func (*TbPendukungTbMasterDataDiri) TableName() string {
	return TableNameTbPendukungTbMasterDataDiri
}
