// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package postgres

import (
	"time"
)

const TableNameTbRequestDriver = "tb_request_drivers"

// TbRequestDriver mapped from table <tb_request_drivers>
type TbRequestDriver struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IDCustomer   int32     `gorm:"column:id_customer" json:"id_customer"`
	IDDriver     int32     `gorm:"column:id_driver" json:"id_driver"`
	NamaCustomer string    `gorm:"column:nama_customer" json:"nama_customer"`
	NamaDriver   string    `gorm:"column:nama_driver" json:"nama_driver"`
	NoDriver     string    `gorm:"column:no_driver" json:"no_driver"`
	TglKerja     time.Time `gorm:"column:tgl_kerja;not null" json:"tgl_kerja"`
	TglSelesai   time.Time `gorm:"column:tgl_selesai;not null" json:"tgl_selesai"`
	LokasiMobil  string    `gorm:"column:lokasi_mobil;not null" json:"lokasi_mobil"`
	Pic          string    `gorm:"column:pic;not null" json:"pic"`
	NoPic        string    `gorm:"column:no_pic;not null" json:"no_pic"`
	FotoMobil    string    `gorm:"column:foto_mobil;not null" json:"foto_mobil"`
}

// TableName TbRequestDriver's table name
func (*TbRequestDriver) TableName() string {
	return TableNameTbRequestDriver
}
