// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package postgres

const TableNameTbServiceJourneyBackup = "tb_service_journey_backup"

// TbServiceJourneyBackup mapped from table <tb_service_journey_backup>
type TbServiceJourneyBackup struct {
	ID                   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IDMasterDataDiri     int32  `gorm:"column:id_master_data_diri" json:"id_master_data_diri"`
	StatusDapatUuck      string `gorm:"column:status_dapat_uuck" json:"status_dapat_uuck"`
	PerluUuck            string `gorm:"column:perlu_uuck" json:"perlu_uuck"`
	TglUuck              string `gorm:"column:tgl_uuck" json:"tgl_uuck"`
	StatusDapatTraining  string `gorm:"column:status_dapat_training" json:"status_dapat_training"`
	PerluTraining        string `gorm:"column:perlu_training" json:"perlu_training"`
	TglTraining          string `gorm:"column:tgl_training" json:"tgl_training"`
	StatusDapatMcu       string `gorm:"column:status_dapat_mcu" json:"status_dapat_mcu"`
	PerluMcu             string `gorm:"column:perlu_mcu" json:"perlu_mcu"`
	TglMcu               string `gorm:"column:tgl_mcu" json:"tgl_mcu"`
	StatusDapatSeragam   string `gorm:"column:status_dapat_seragam" json:"status_dapat_seragam"`
	PerluSeragam         string `gorm:"column:perlu_seragam" json:"perlu_seragam"`
	TglSeragam           string `gorm:"column:tgl_seragam" json:"tgl_seragam"`
	StatusDapatThr       string `gorm:"column:status_dapat_thr" json:"status_dapat_thr"`
	PerluThr             string `gorm:"column:perlu_thr" json:"perlu_thr"`
	TglThr               string `gorm:"column:tgl_thr" json:"tgl_thr"`
	StatusDapatLaporPkwt string `gorm:"column:status_dapat_lapor_pkwt" json:"status_dapat_lapor_pkwt"`
	PerluLaporPkwt       string `gorm:"column:perlu_lapor_pkwt" json:"perlu_lapor_pkwt"`
	TglLaporPkwt         string `gorm:"column:tgl_lapor_pkwt" json:"tgl_lapor_pkwt"`
	TglTtdPkwt           string `gorm:"column:tgl_ttd_pkwt" json:"tgl_ttd_pkwt"`
	StartPkwtDriver      string `gorm:"column:start_pkwt_driver" json:"start_pkwt_driver"`
	EndPkwtDriver        string `gorm:"column:end_pkwt_driver" json:"end_pkwt_driver"`
	Status               string `gorm:"column:status" json:"status"`
	Keterangan           string `gorm:"column:keterangan" json:"keterangan"`
}

// TableName TbServiceJourneyBackup's table name
func (*TbServiceJourneyBackup) TableName() string {
	return TableNameTbServiceJourneyBackup
}
