// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package postgres

const TableNameUser = "Users"

// User mapped from table <Users>
type User struct {
	Fullname string `gorm:"column:fullname" json:"fullname"`
	Email    string `gorm:"column:email;not null" json:"email"`
	Password string `gorm:"column:password" json:"password"`
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
